
namespace SMARTLİBRARY
{
    partial class UyeKitaplarim
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UyeKitaplarim));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.yazar_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ara_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AraBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.kitapDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.ozet_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tur_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.isim_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.baski_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.bitis_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.basla_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.kitapDataGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoScroll = true;
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.LightGray;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(452, 12);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(471, 350);
            this.flowLayoutPanel1.TabIndex = 84;
            // 
            // yazar_txt
            // 
            this.yazar_txt.AcceptsReturn = false;
            this.yazar_txt.AcceptsTab = false;
            this.yazar_txt.AnimationSpeed = 200;
            this.yazar_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.yazar_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.yazar_txt.BackColor = System.Drawing.Color.Transparent;
            this.yazar_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("yazar_txt.BackgroundImage")));
            this.yazar_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.yazar_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.yazar_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.yazar_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.yazar_txt.BorderRadius = 1;
            this.yazar_txt.BorderThickness = 1;
            this.yazar_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.yazar_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.yazar_txt.DefaultText = "";
            this.yazar_txt.FillColor = System.Drawing.Color.White;
            this.yazar_txt.HideSelection = true;
            this.yazar_txt.IconLeft = null;
            this.yazar_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.IconPadding = 10;
            this.yazar_txt.IconRight = null;
            this.yazar_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.Lines = new string[0];
            this.yazar_txt.Location = new System.Drawing.Point(278, 12);
            this.yazar_txt.MaxLength = 32767;
            this.yazar_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.yazar_txt.Modified = false;
            this.yazar_txt.Multiline = false;
            this.yazar_txt.Name = "yazar_txt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.yazar_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnIdleState = stateProperties4;
            this.yazar_txt.Padding = new System.Windows.Forms.Padding(3);
            this.yazar_txt.PasswordChar = '\0';
            this.yazar_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.yazar_txt.PlaceholderText = "Yazar";
            this.yazar_txt.ReadOnly = false;
            this.yazar_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.yazar_txt.SelectedText = "";
            this.yazar_txt.SelectionLength = 0;
            this.yazar_txt.SelectionStart = 0;
            this.yazar_txt.ShortcutsEnabled = true;
            this.yazar_txt.Size = new System.Drawing.Size(168, 37);
            this.yazar_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.yazar_txt.TabIndex = 76;
            this.yazar_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.yazar_txt.TextMarginBottom = 0;
            this.yazar_txt.TextMarginLeft = 3;
            this.yazar_txt.TextMarginTop = 0;
            this.yazar_txt.TextPlaceholder = "Yazar";
            this.yazar_txt.UseSystemPasswordChar = false;
            this.yazar_txt.WordWrap = true;
            // 
            // ara_txt
            // 
            this.ara_txt.AcceptsReturn = false;
            this.ara_txt.AcceptsTab = false;
            this.ara_txt.AnimationSpeed = 200;
            this.ara_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ara_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ara_txt.BackColor = System.Drawing.Color.Transparent;
            this.ara_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ara_txt.BackgroundImage")));
            this.ara_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ara_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ara_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ara_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ara_txt.BorderRadius = 1;
            this.ara_txt.BorderThickness = 1;
            this.ara_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ara_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ara_txt.DefaultText = "";
            this.ara_txt.FillColor = System.Drawing.Color.White;
            this.ara_txt.HideSelection = true;
            this.ara_txt.IconLeft = null;
            this.ara_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.IconPadding = 10;
            this.ara_txt.IconRight = null;
            this.ara_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.Lines = new string[0];
            this.ara_txt.Location = new System.Drawing.Point(215, 282);
            this.ara_txt.MaxLength = 32767;
            this.ara_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ara_txt.Modified = false;
            this.ara_txt.Multiline = false;
            this.ara_txt.Name = "ara_txt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ara_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnIdleState = stateProperties8;
            this.ara_txt.Padding = new System.Windows.Forms.Padding(3);
            this.ara_txt.PasswordChar = '\0';
            this.ara_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ara_txt.PlaceholderText = "Kitap İsmi";
            this.ara_txt.ReadOnly = false;
            this.ara_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ara_txt.SelectedText = "";
            this.ara_txt.SelectionLength = 0;
            this.ara_txt.SelectionStart = 0;
            this.ara_txt.ShortcutsEnabled = true;
            this.ara_txt.Size = new System.Drawing.Size(231, 37);
            this.ara_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ara_txt.TabIndex = 82;
            this.ara_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ara_txt.TextMarginBottom = 0;
            this.ara_txt.TextMarginLeft = 3;
            this.ara_txt.TextMarginTop = 0;
            this.ara_txt.TextPlaceholder = "Kitap İsmi";
            this.ara_txt.UseSystemPasswordChar = false;
            this.ara_txt.WordWrap = true;
            // 
            // AraBtn
            // 
            this.AraBtn.AllowAnimations = true;
            this.AraBtn.AllowMouseEffects = true;
            this.AraBtn.AllowToggling = false;
            this.AraBtn.AnimationSpeed = 200;
            this.AraBtn.AutoGenerateColors = false;
            this.AraBtn.AutoRoundBorders = false;
            this.AraBtn.AutoSizeLeftIcon = true;
            this.AraBtn.AutoSizeRightIcon = true;
            this.AraBtn.BackColor = System.Drawing.Color.Transparent;
            this.AraBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.AraBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AraBtn.BackgroundImage")));
            this.AraBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.ButtonText = "Ara";
            this.AraBtn.ButtonTextMarginLeft = 0;
            this.AraBtn.ColorContrastOnClick = 45;
            this.AraBtn.ColorContrastOnHover = 45;
            this.AraBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AraBtn.CustomizableEdges = borderEdges1;
            this.AraBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AraBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AraBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AraBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AraBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AraBtn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.AraBtn.ForeColor = System.Drawing.Color.White;
            this.AraBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AraBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AraBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AraBtn.IconMarginLeft = 11;
            this.AraBtn.IconPadding = 10;
            this.AraBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AraBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AraBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AraBtn.IconSize = 25;
            this.AraBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.IdleBorderRadius = 1;
            this.AraBtn.IdleBorderThickness = 1;
            this.AraBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.IdleIconLeftImage = null;
            this.AraBtn.IdleIconRightImage = null;
            this.AraBtn.IndicateFocus = false;
            this.AraBtn.Location = new System.Drawing.Point(215, 325);
            this.AraBtn.Name = "AraBtn";
            this.AraBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AraBtn.OnDisabledState.BorderRadius = 1;
            this.AraBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnDisabledState.BorderThickness = 1;
            this.AraBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AraBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AraBtn.OnDisabledState.IconLeftImage = null;
            this.AraBtn.OnDisabledState.IconRightImage = null;
            this.AraBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AraBtn.onHoverState.BorderRadius = 1;
            this.AraBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.onHoverState.BorderThickness = 1;
            this.AraBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AraBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.onHoverState.IconLeftImage = null;
            this.AraBtn.onHoverState.IconRightImage = null;
            this.AraBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.OnIdleState.BorderRadius = 1;
            this.AraBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnIdleState.BorderThickness = 1;
            this.AraBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.OnIdleState.IconLeftImage = null;
            this.AraBtn.OnIdleState.IconRightImage = null;
            this.AraBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AraBtn.OnPressedState.BorderRadius = 1;
            this.AraBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnPressedState.BorderThickness = 1;
            this.AraBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AraBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.OnPressedState.IconLeftImage = null;
            this.AraBtn.OnPressedState.IconRightImage = null;
            this.AraBtn.Size = new System.Drawing.Size(231, 37);
            this.AraBtn.TabIndex = 81;
            this.AraBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AraBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AraBtn.TextMarginLeft = 0;
            this.AraBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AraBtn.UseDefaultRadiusAndThickness = true;
            // 
            // kitapDataGridView
            // 
            this.kitapDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.kitapDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.kitapDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.kitapDataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.kitapDataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.kitapDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.kitapDataGridView.ColumnHeadersHeight = 40;
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.kitapDataGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.kitapDataGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.kitapDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.Name = null;
            this.kitapDataGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.kitapDataGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.kitapDataGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.kitapDataGridView.EnableHeadersVisualStyles = false;
            this.kitapDataGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.kitapDataGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.kitapDataGridView.HeaderForeColor = System.Drawing.Color.White;
            this.kitapDataGridView.Location = new System.Drawing.Point(12, 368);
            this.kitapDataGridView.Name = "kitapDataGridView";
            this.kitapDataGridView.RowHeadersVisible = false;
            this.kitapDataGridView.RowHeadersWidth = 62;
            this.kitapDataGridView.RowTemplate.Height = 40;
            this.kitapDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.kitapDataGridView.Size = new System.Drawing.Size(911, 219);
            this.kitapDataGridView.TabIndex = 80;
            this.kitapDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // ozet_txt
            // 
            this.ozet_txt.AcceptsReturn = false;
            this.ozet_txt.AcceptsTab = false;
            this.ozet_txt.AnimationSpeed = 200;
            this.ozet_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ozet_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ozet_txt.BackColor = System.Drawing.Color.Transparent;
            this.ozet_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ozet_txt.BackgroundImage")));
            this.ozet_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ozet_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ozet_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ozet_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ozet_txt.BorderRadius = 1;
            this.ozet_txt.BorderThickness = 1;
            this.ozet_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ozet_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ozet_txt.DefaultText = "";
            this.ozet_txt.FillColor = System.Drawing.Color.White;
            this.ozet_txt.HideSelection = true;
            this.ozet_txt.IconLeft = null;
            this.ozet_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.IconPadding = 10;
            this.ozet_txt.IconRight = null;
            this.ozet_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.Lines = new string[0];
            this.ozet_txt.Location = new System.Drawing.Point(12, 98);
            this.ozet_txt.MaxLength = 32767;
            this.ozet_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ozet_txt.Modified = false;
            this.ozet_txt.Multiline = true;
            this.ozet_txt.Name = "ozet_txt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ozet_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnIdleState = stateProperties12;
            this.ozet_txt.Padding = new System.Windows.Forms.Padding(3);
            this.ozet_txt.PasswordChar = '\0';
            this.ozet_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ozet_txt.PlaceholderText = "Özet";
            this.ozet_txt.ReadOnly = false;
            this.ozet_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ozet_txt.SelectedText = "";
            this.ozet_txt.SelectionLength = 0;
            this.ozet_txt.SelectionStart = 0;
            this.ozet_txt.ShortcutsEnabled = true;
            this.ozet_txt.Size = new System.Drawing.Size(260, 178);
            this.ozet_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ozet_txt.TabIndex = 78;
            this.ozet_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ozet_txt.TextMarginBottom = 0;
            this.ozet_txt.TextMarginLeft = 3;
            this.ozet_txt.TextMarginTop = 0;
            this.ozet_txt.TextPlaceholder = "Özet";
            this.ozet_txt.UseSystemPasswordChar = false;
            this.ozet_txt.WordWrap = true;
            // 
            // tur_txt
            // 
            this.tur_txt.AcceptsReturn = false;
            this.tur_txt.AcceptsTab = false;
            this.tur_txt.AnimationSpeed = 200;
            this.tur_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tur_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tur_txt.BackColor = System.Drawing.Color.Transparent;
            this.tur_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tur_txt.BackgroundImage")));
            this.tur_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tur_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tur_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tur_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.tur_txt.BorderRadius = 1;
            this.tur_txt.BorderThickness = 1;
            this.tur_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tur_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tur_txt.DefaultText = "";
            this.tur_txt.FillColor = System.Drawing.Color.White;
            this.tur_txt.HideSelection = true;
            this.tur_txt.IconLeft = null;
            this.tur_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.IconPadding = 10;
            this.tur_txt.IconRight = null;
            this.tur_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.Lines = new string[0];
            this.tur_txt.Location = new System.Drawing.Point(12, 55);
            this.tur_txt.MaxLength = 32767;
            this.tur_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.tur_txt.Modified = false;
            this.tur_txt.Multiline = false;
            this.tur_txt.Name = "tur_txt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tur_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnIdleState = stateProperties16;
            this.tur_txt.Padding = new System.Windows.Forms.Padding(3);
            this.tur_txt.PasswordChar = '\0';
            this.tur_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.tur_txt.PlaceholderText = "Tür";
            this.tur_txt.ReadOnly = false;
            this.tur_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tur_txt.SelectedText = "";
            this.tur_txt.SelectionLength = 0;
            this.tur_txt.SelectionStart = 0;
            this.tur_txt.ShortcutsEnabled = true;
            this.tur_txt.Size = new System.Drawing.Size(260, 37);
            this.tur_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tur_txt.TabIndex = 77;
            this.tur_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tur_txt.TextMarginBottom = 0;
            this.tur_txt.TextMarginLeft = 3;
            this.tur_txt.TextMarginTop = 0;
            this.tur_txt.TextPlaceholder = "Tür";
            this.tur_txt.UseSystemPasswordChar = false;
            this.tur_txt.WordWrap = true;
            // 
            // isim_txt
            // 
            this.isim_txt.AcceptsReturn = false;
            this.isim_txt.AcceptsTab = false;
            this.isim_txt.AnimationSpeed = 200;
            this.isim_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.isim_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.isim_txt.BackColor = System.Drawing.Color.Transparent;
            this.isim_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("isim_txt.BackgroundImage")));
            this.isim_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.isim_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.isim_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.isim_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.isim_txt.BorderRadius = 1;
            this.isim_txt.BorderThickness = 1;
            this.isim_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.isim_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.isim_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.isim_txt.DefaultText = "";
            this.isim_txt.FillColor = System.Drawing.Color.White;
            this.isim_txt.HideSelection = true;
            this.isim_txt.IconLeft = null;
            this.isim_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.isim_txt.IconPadding = 10;
            this.isim_txt.IconRight = null;
            this.isim_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.isim_txt.Lines = new string[0];
            this.isim_txt.Location = new System.Drawing.Point(12, 12);
            this.isim_txt.MaxLength = 32767;
            this.isim_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.isim_txt.Modified = false;
            this.isim_txt.Multiline = false;
            this.isim_txt.Name = "isim_txt";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.isim_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.isim_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.isim_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.isim_txt.OnIdleState = stateProperties20;
            this.isim_txt.Padding = new System.Windows.Forms.Padding(3);
            this.isim_txt.PasswordChar = '\0';
            this.isim_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.isim_txt.PlaceholderText = "Kitap İsim";
            this.isim_txt.ReadOnly = false;
            this.isim_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.isim_txt.SelectedText = "";
            this.isim_txt.SelectionLength = 0;
            this.isim_txt.SelectionStart = 0;
            this.isim_txt.ShortcutsEnabled = true;
            this.isim_txt.Size = new System.Drawing.Size(260, 37);
            this.isim_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.isim_txt.TabIndex = 75;
            this.isim_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.isim_txt.TextMarginBottom = 0;
            this.isim_txt.TextMarginLeft = 3;
            this.isim_txt.TextMarginTop = 0;
            this.isim_txt.TextPlaceholder = "Kitap İsim";
            this.isim_txt.UseSystemPasswordChar = false;
            this.isim_txt.WordWrap = true;
            // 
            // baski_txt
            // 
            this.baski_txt.AcceptsReturn = false;
            this.baski_txt.AcceptsTab = false;
            this.baski_txt.AnimationSpeed = 200;
            this.baski_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.baski_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.baski_txt.BackColor = System.Drawing.Color.Transparent;
            this.baski_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("baski_txt.BackgroundImage")));
            this.baski_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.baski_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.baski_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.baski_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.baski_txt.BorderRadius = 1;
            this.baski_txt.BorderThickness = 1;
            this.baski_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.baski_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.baski_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.baski_txt.DefaultText = "";
            this.baski_txt.FillColor = System.Drawing.Color.White;
            this.baski_txt.HideSelection = true;
            this.baski_txt.IconLeft = null;
            this.baski_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.baski_txt.IconPadding = 10;
            this.baski_txt.IconRight = null;
            this.baski_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.baski_txt.Lines = new string[0];
            this.baski_txt.Location = new System.Drawing.Point(278, 55);
            this.baski_txt.MaxLength = 32767;
            this.baski_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.baski_txt.Modified = false;
            this.baski_txt.Multiline = false;
            this.baski_txt.Name = "baski_txt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.baski_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.baski_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.baski_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.baski_txt.OnIdleState = stateProperties24;
            this.baski_txt.Padding = new System.Windows.Forms.Padding(3);
            this.baski_txt.PasswordChar = '\0';
            this.baski_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.baski_txt.PlaceholderText = "Baskı";
            this.baski_txt.ReadOnly = false;
            this.baski_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.baski_txt.SelectedText = "";
            this.baski_txt.SelectionLength = 0;
            this.baski_txt.SelectionStart = 0;
            this.baski_txt.ShortcutsEnabled = true;
            this.baski_txt.Size = new System.Drawing.Size(168, 37);
            this.baski_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.baski_txt.TabIndex = 85;
            this.baski_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.baski_txt.TextMarginBottom = 0;
            this.baski_txt.TextMarginLeft = 3;
            this.baski_txt.TextMarginTop = 0;
            this.baski_txt.TextPlaceholder = "Baskı";
            this.baski_txt.UseSystemPasswordChar = false;
            this.baski_txt.WordWrap = true;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = global::SMARTLİBRARY.Properties.Resources.m;
            this.pictureBox2.Location = new System.Drawing.Point(278, 98);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(168, 178);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 86;
            this.pictureBox2.TabStop = false;
            // 
            // bitis_txt
            // 
            this.bitis_txt.AcceptsReturn = false;
            this.bitis_txt.AcceptsTab = false;
            this.bitis_txt.AnimationSpeed = 200;
            this.bitis_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bitis_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bitis_txt.BackColor = System.Drawing.Color.Transparent;
            this.bitis_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bitis_txt.BackgroundImage")));
            this.bitis_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bitis_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bitis_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bitis_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.bitis_txt.BorderRadius = 1;
            this.bitis_txt.BorderThickness = 1;
            this.bitis_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bitis_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bitis_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bitis_txt.DefaultText = "";
            this.bitis_txt.FillColor = System.Drawing.Color.White;
            this.bitis_txt.HideSelection = true;
            this.bitis_txt.IconLeft = null;
            this.bitis_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bitis_txt.IconPadding = 10;
            this.bitis_txt.IconRight = null;
            this.bitis_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bitis_txt.Lines = new string[0];
            this.bitis_txt.Location = new System.Drawing.Point(12, 325);
            this.bitis_txt.MaxLength = 32767;
            this.bitis_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.bitis_txt.Modified = false;
            this.bitis_txt.Multiline = false;
            this.bitis_txt.Name = "bitis_txt";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bitis_txt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bitis_txt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bitis_txt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bitis_txt.OnIdleState = stateProperties28;
            this.bitis_txt.Padding = new System.Windows.Forms.Padding(3);
            this.bitis_txt.PasswordChar = '\0';
            this.bitis_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.bitis_txt.PlaceholderText = "Bitiş Tarihi";
            this.bitis_txt.ReadOnly = false;
            this.bitis_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bitis_txt.SelectedText = "";
            this.bitis_txt.SelectionLength = 0;
            this.bitis_txt.SelectionStart = 0;
            this.bitis_txt.ShortcutsEnabled = true;
            this.bitis_txt.Size = new System.Drawing.Size(197, 37);
            this.bitis_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bitis_txt.TabIndex = 87;
            this.bitis_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bitis_txt.TextMarginBottom = 0;
            this.bitis_txt.TextMarginLeft = 3;
            this.bitis_txt.TextMarginTop = 0;
            this.bitis_txt.TextPlaceholder = "Bitiş Tarihi";
            this.bitis_txt.UseSystemPasswordChar = false;
            this.bitis_txt.WordWrap = true;
            // 
            // basla_txt
            // 
            this.basla_txt.AcceptsReturn = false;
            this.basla_txt.AcceptsTab = false;
            this.basla_txt.AnimationSpeed = 200;
            this.basla_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.basla_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.basla_txt.BackColor = System.Drawing.Color.Transparent;
            this.basla_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("basla_txt.BackgroundImage")));
            this.basla_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.basla_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.basla_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.basla_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.basla_txt.BorderRadius = 1;
            this.basla_txt.BorderThickness = 1;
            this.basla_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.basla_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.basla_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.basla_txt.DefaultText = "";
            this.basla_txt.FillColor = System.Drawing.Color.White;
            this.basla_txt.HideSelection = true;
            this.basla_txt.IconLeft = null;
            this.basla_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.basla_txt.IconPadding = 10;
            this.basla_txt.IconRight = null;
            this.basla_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.basla_txt.Lines = new string[0];
            this.basla_txt.Location = new System.Drawing.Point(12, 282);
            this.basla_txt.MaxLength = 32767;
            this.basla_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.basla_txt.Modified = false;
            this.basla_txt.Multiline = false;
            this.basla_txt.Name = "basla_txt";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.basla_txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.basla_txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.basla_txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.basla_txt.OnIdleState = stateProperties32;
            this.basla_txt.Padding = new System.Windows.Forms.Padding(3);
            this.basla_txt.PasswordChar = '\0';
            this.basla_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.basla_txt.PlaceholderText = "Başlangıç Tarihi";
            this.basla_txt.ReadOnly = false;
            this.basla_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.basla_txt.SelectedText = "";
            this.basla_txt.SelectionLength = 0;
            this.basla_txt.SelectionStart = 0;
            this.basla_txt.ShortcutsEnabled = true;
            this.basla_txt.Size = new System.Drawing.Size(197, 37);
            this.basla_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.basla_txt.TabIndex = 88;
            this.basla_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.basla_txt.TextMarginBottom = 0;
            this.basla_txt.TextMarginLeft = 3;
            this.basla_txt.TextMarginTop = 0;
            this.basla_txt.TextPlaceholder = "Başlangıç Tarihi";
            this.basla_txt.UseSystemPasswordChar = false;
            this.basla_txt.WordWrap = true;
            // 
            // UyeKitaplarim
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(935, 599);
            this.Controls.Add(this.basla_txt);
            this.Controls.Add(this.bitis_txt);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.baski_txt);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.yazar_txt);
            this.Controls.Add(this.ara_txt);
            this.Controls.Add(this.AraBtn);
            this.Controls.Add(this.kitapDataGridView);
            this.Controls.Add(this.ozet_txt);
            this.Controls.Add(this.tur_txt);
            this.Controls.Add(this.isim_txt);
            this.Name = "UyeKitaplarim";
            this.Text = "Kitaplarım";
            this.Load += new System.EventHandler(this.UyeKitaplarim_Load);
            ((System.ComponentModel.ISupportInitialize)(this.kitapDataGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox yazar_txt;
        private Bunifu.UI.WinForms.BunifuTextBox ara_txt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AraBtn;
        private Bunifu.UI.WinForms.BunifuDataGridView kitapDataGridView;
        private Bunifu.UI.WinForms.BunifuTextBox ozet_txt;
        private Bunifu.UI.WinForms.BunifuTextBox tur_txt;
        private Bunifu.UI.WinForms.BunifuTextBox isim_txt;
        private Bunifu.UI.WinForms.BunifuTextBox baski_txt;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuTextBox bitis_txt;
        private Bunifu.UI.WinForms.BunifuTextBox basla_txt;
    }
}