
namespace SMARTLİBRARY
{
    partial class UyeKitaplık
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UyeKitaplık));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.TemizleBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.sayfa_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dil_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.ozet_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tur_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.yazar_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.İsim_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.EgitimBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.BilimBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.TarihBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.TeknolojiBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.EdebiyatBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.SanatBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.AskBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.AksiyonBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.FelsefeBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.BilimKurguBtn = new Bunifu.Framework.UI.BunifuTileButton();
            this.PolisiyeButton = new Bunifu.Framework.UI.BunifuTileButton();
            this.fantastikButton = new Bunifu.Framework.UI.BunifuTileButton();
            this.kitaplikDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.AraBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.kitapAra_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.baski_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kitaplikDataGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // TemizleBtn
            // 
            this.TemizleBtn.AllowAnimations = true;
            this.TemizleBtn.AllowMouseEffects = true;
            this.TemizleBtn.AllowToggling = false;
            this.TemizleBtn.AnimationSpeed = 200;
            this.TemizleBtn.AutoGenerateColors = false;
            this.TemizleBtn.AutoRoundBorders = false;
            this.TemizleBtn.AutoSizeLeftIcon = true;
            this.TemizleBtn.AutoSizeRightIcon = true;
            this.TemizleBtn.BackColor = System.Drawing.Color.Transparent;
            this.TemizleBtn.BackColor1 = System.Drawing.Color.DarkSlateGray;
            this.TemizleBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TemizleBtn.BackgroundImage")));
            this.TemizleBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TemizleBtn.ButtonText = "Temizle";
            this.TemizleBtn.ButtonTextMarginLeft = 0;
            this.TemizleBtn.ColorContrastOnClick = 45;
            this.TemizleBtn.ColorContrastOnHover = 45;
            this.TemizleBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.TemizleBtn.CustomizableEdges = borderEdges1;
            this.TemizleBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.TemizleBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TemizleBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TemizleBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TemizleBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.TemizleBtn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.TemizleBtn.ForeColor = System.Drawing.Color.White;
            this.TemizleBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.TemizleBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.TemizleBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.TemizleBtn.IconMarginLeft = 11;
            this.TemizleBtn.IconPadding = 10;
            this.TemizleBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.TemizleBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.TemizleBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.TemizleBtn.IconSize = 25;
            this.TemizleBtn.IdleBorderColor = System.Drawing.Color.DarkSlateGray;
            this.TemizleBtn.IdleBorderRadius = 1;
            this.TemizleBtn.IdleBorderThickness = 1;
            this.TemizleBtn.IdleFillColor = System.Drawing.Color.DarkSlateGray;
            this.TemizleBtn.IdleIconLeftImage = null;
            this.TemizleBtn.IdleIconRightImage = null;
            this.TemizleBtn.IndicateFocus = false;
            this.TemizleBtn.Location = new System.Drawing.Point(770, 539);
            this.TemizleBtn.Name = "TemizleBtn";
            this.TemizleBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.TemizleBtn.OnDisabledState.BorderRadius = 1;
            this.TemizleBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TemizleBtn.OnDisabledState.BorderThickness = 1;
            this.TemizleBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TemizleBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.TemizleBtn.OnDisabledState.IconLeftImage = null;
            this.TemizleBtn.OnDisabledState.IconRightImage = null;
            this.TemizleBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TemizleBtn.onHoverState.BorderRadius = 1;
            this.TemizleBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TemizleBtn.onHoverState.BorderThickness = 1;
            this.TemizleBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TemizleBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.TemizleBtn.onHoverState.IconLeftImage = null;
            this.TemizleBtn.onHoverState.IconRightImage = null;
            this.TemizleBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.TemizleBtn.OnIdleState.BorderRadius = 1;
            this.TemizleBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TemizleBtn.OnIdleState.BorderThickness = 1;
            this.TemizleBtn.OnIdleState.FillColor = System.Drawing.Color.DarkSlateGray;
            this.TemizleBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.TemizleBtn.OnIdleState.IconLeftImage = null;
            this.TemizleBtn.OnIdleState.IconRightImage = null;
            this.TemizleBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TemizleBtn.OnPressedState.BorderRadius = 1;
            this.TemizleBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.TemizleBtn.OnPressedState.BorderThickness = 1;
            this.TemizleBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.TemizleBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.TemizleBtn.OnPressedState.IconLeftImage = null;
            this.TemizleBtn.OnPressedState.IconRightImage = null;
            this.TemizleBtn.Size = new System.Drawing.Size(176, 37);
            this.TemizleBtn.TabIndex = 117;
            this.TemizleBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.TemizleBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.TemizleBtn.TextMarginLeft = 0;
            this.TemizleBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.TemizleBtn.UseDefaultRadiusAndThickness = true;
            this.TemizleBtn.Click += new System.EventHandler(this.TemizleBtn_Click);
            // 
            // sayfa_txt
            // 
            this.sayfa_txt.AcceptsReturn = false;
            this.sayfa_txt.AcceptsTab = false;
            this.sayfa_txt.AnimationSpeed = 200;
            this.sayfa_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sayfa_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sayfa_txt.BackColor = System.Drawing.Color.Transparent;
            this.sayfa_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sayfa_txt.BackgroundImage")));
            this.sayfa_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.sayfa_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sayfa_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sayfa_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.sayfa_txt.BorderRadius = 1;
            this.sayfa_txt.BorderThickness = 1;
            this.sayfa_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sayfa_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sayfa_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.sayfa_txt.DefaultText = "";
            this.sayfa_txt.FillColor = System.Drawing.Color.White;
            this.sayfa_txt.HideSelection = true;
            this.sayfa_txt.IconLeft = null;
            this.sayfa_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sayfa_txt.IconPadding = 10;
            this.sayfa_txt.IconRight = null;
            this.sayfa_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sayfa_txt.Lines = new string[0];
            this.sayfa_txt.Location = new System.Drawing.Point(12, 98);
            this.sayfa_txt.MaxLength = 32767;
            this.sayfa_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.sayfa_txt.Modified = false;
            this.sayfa_txt.Multiline = false;
            this.sayfa_txt.Name = "sayfa_txt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sayfa_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sayfa_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sayfa_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sayfa_txt.OnIdleState = stateProperties4;
            this.sayfa_txt.Padding = new System.Windows.Forms.Padding(3);
            this.sayfa_txt.PasswordChar = '\0';
            this.sayfa_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.sayfa_txt.PlaceholderText = "Sayfa Sayısı";
            this.sayfa_txt.ReadOnly = false;
            this.sayfa_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sayfa_txt.SelectedText = "";
            this.sayfa_txt.SelectionLength = 0;
            this.sayfa_txt.SelectionStart = 0;
            this.sayfa_txt.ShortcutsEnabled = true;
            this.sayfa_txt.Size = new System.Drawing.Size(244, 37);
            this.sayfa_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sayfa_txt.TabIndex = 116;
            this.sayfa_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sayfa_txt.TextMarginBottom = 0;
            this.sayfa_txt.TextMarginLeft = 3;
            this.sayfa_txt.TextMarginTop = 0;
            this.sayfa_txt.TextPlaceholder = "Sayfa Sayısı";
            this.sayfa_txt.UseSystemPasswordChar = false;
            this.sayfa_txt.WordWrap = true;
            // 
            // dil_txt
            // 
            this.dil_txt.AcceptsReturn = false;
            this.dil_txt.AcceptsTab = false;
            this.dil_txt.AnimationSpeed = 200;
            this.dil_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.dil_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.dil_txt.BackColor = System.Drawing.Color.Transparent;
            this.dil_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dil_txt.BackgroundImage")));
            this.dil_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.dil_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dil_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.dil_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.dil_txt.BorderRadius = 1;
            this.dil_txt.BorderThickness = 1;
            this.dil_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.dil_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.dil_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.dil_txt.DefaultText = "";
            this.dil_txt.FillColor = System.Drawing.Color.White;
            this.dil_txt.HideSelection = true;
            this.dil_txt.IconLeft = null;
            this.dil_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.dil_txt.IconPadding = 10;
            this.dil_txt.IconRight = null;
            this.dil_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.dil_txt.Lines = new string[0];
            this.dil_txt.Location = new System.Drawing.Point(262, 55);
            this.dil_txt.MaxLength = 32767;
            this.dil_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.dil_txt.Modified = false;
            this.dil_txt.Multiline = false;
            this.dil_txt.Name = "dil_txt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dil_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.dil_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dil_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dil_txt.OnIdleState = stateProperties8;
            this.dil_txt.Padding = new System.Windows.Forms.Padding(3);
            this.dil_txt.PasswordChar = '\0';
            this.dil_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.dil_txt.PlaceholderText = "Dil";
            this.dil_txt.ReadOnly = false;
            this.dil_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dil_txt.SelectedText = "";
            this.dil_txt.SelectionLength = 0;
            this.dil_txt.SelectionStart = 0;
            this.dil_txt.ShortcutsEnabled = true;
            this.dil_txt.Size = new System.Drawing.Size(180, 37);
            this.dil_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.dil_txt.TabIndex = 115;
            this.dil_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.dil_txt.TextMarginBottom = 0;
            this.dil_txt.TextMarginLeft = 3;
            this.dil_txt.TextMarginTop = 0;
            this.dil_txt.TextPlaceholder = "Dil";
            this.dil_txt.UseSystemPasswordChar = false;
            this.dil_txt.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(445, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(130, 209);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 114;
            this.pictureBox1.TabStop = false;
            // 
            // ozet_txt
            // 
            this.ozet_txt.AcceptsReturn = false;
            this.ozet_txt.AcceptsTab = false;
            this.ozet_txt.AnimationSpeed = 200;
            this.ozet_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ozet_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ozet_txt.BackColor = System.Drawing.Color.Transparent;
            this.ozet_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ozet_txt.BackgroundImage")));
            this.ozet_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ozet_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ozet_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ozet_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ozet_txt.BorderRadius = 1;
            this.ozet_txt.BorderThickness = 1;
            this.ozet_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ozet_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ozet_txt.DefaultText = "";
            this.ozet_txt.FillColor = System.Drawing.Color.White;
            this.ozet_txt.HideSelection = true;
            this.ozet_txt.IconLeft = null;
            this.ozet_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.IconPadding = 10;
            this.ozet_txt.IconRight = null;
            this.ozet_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.Lines = new string[0];
            this.ozet_txt.Location = new System.Drawing.Point(12, 141);
            this.ozet_txt.MaxLength = 32767;
            this.ozet_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.ozet_txt.Modified = false;
            this.ozet_txt.Multiline = true;
            this.ozet_txt.Name = "ozet_txt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ozet_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnIdleState = stateProperties12;
            this.ozet_txt.Padding = new System.Windows.Forms.Padding(3);
            this.ozet_txt.PasswordChar = '\0';
            this.ozet_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ozet_txt.PlaceholderText = "Özet";
            this.ozet_txt.ReadOnly = false;
            this.ozet_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ozet_txt.SelectedText = "";
            this.ozet_txt.SelectionLength = 0;
            this.ozet_txt.SelectionStart = 0;
            this.ozet_txt.ShortcutsEnabled = true;
            this.ozet_txt.Size = new System.Drawing.Size(430, 80);
            this.ozet_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ozet_txt.TabIndex = 113;
            this.ozet_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ozet_txt.TextMarginBottom = 0;
            this.ozet_txt.TextMarginLeft = 3;
            this.ozet_txt.TextMarginTop = 0;
            this.ozet_txt.TextPlaceholder = "Özet";
            this.ozet_txt.UseSystemPasswordChar = false;
            this.ozet_txt.WordWrap = true;
            // 
            // tur_txt
            // 
            this.tur_txt.AcceptsReturn = false;
            this.tur_txt.AcceptsTab = false;
            this.tur_txt.AnimationSpeed = 200;
            this.tur_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tur_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tur_txt.BackColor = System.Drawing.Color.Transparent;
            this.tur_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tur_txt.BackgroundImage")));
            this.tur_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tur_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tur_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tur_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.tur_txt.BorderRadius = 1;
            this.tur_txt.BorderThickness = 1;
            this.tur_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tur_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tur_txt.DefaultText = "";
            this.tur_txt.FillColor = System.Drawing.Color.White;
            this.tur_txt.HideSelection = true;
            this.tur_txt.IconLeft = null;
            this.tur_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.IconPadding = 10;
            this.tur_txt.IconRight = null;
            this.tur_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.Lines = new string[0];
            this.tur_txt.Location = new System.Drawing.Point(262, 12);
            this.tur_txt.MaxLength = 32767;
            this.tur_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.tur_txt.Modified = false;
            this.tur_txt.Multiline = false;
            this.tur_txt.Name = "tur_txt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tur_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnIdleState = stateProperties16;
            this.tur_txt.Padding = new System.Windows.Forms.Padding(3);
            this.tur_txt.PasswordChar = '\0';
            this.tur_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.tur_txt.PlaceholderText = "Tür";
            this.tur_txt.ReadOnly = false;
            this.tur_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tur_txt.SelectedText = "";
            this.tur_txt.SelectionLength = 0;
            this.tur_txt.SelectionStart = 0;
            this.tur_txt.ShortcutsEnabled = true;
            this.tur_txt.Size = new System.Drawing.Size(180, 37);
            this.tur_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tur_txt.TabIndex = 112;
            this.tur_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tur_txt.TextMarginBottom = 0;
            this.tur_txt.TextMarginLeft = 3;
            this.tur_txt.TextMarginTop = 0;
            this.tur_txt.TextPlaceholder = "Tür";
            this.tur_txt.UseSystemPasswordChar = false;
            this.tur_txt.WordWrap = true;
            // 
            // yazar_txt
            // 
            this.yazar_txt.AcceptsReturn = false;
            this.yazar_txt.AcceptsTab = false;
            this.yazar_txt.AnimationSpeed = 200;
            this.yazar_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.yazar_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.yazar_txt.BackColor = System.Drawing.Color.Transparent;
            this.yazar_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("yazar_txt.BackgroundImage")));
            this.yazar_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.yazar_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.yazar_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.yazar_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.yazar_txt.BorderRadius = 1;
            this.yazar_txt.BorderThickness = 1;
            this.yazar_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.yazar_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.yazar_txt.DefaultText = "";
            this.yazar_txt.FillColor = System.Drawing.Color.White;
            this.yazar_txt.HideSelection = true;
            this.yazar_txt.IconLeft = null;
            this.yazar_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.IconPadding = 10;
            this.yazar_txt.IconRight = null;
            this.yazar_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.Lines = new string[0];
            this.yazar_txt.Location = new System.Drawing.Point(12, 55);
            this.yazar_txt.MaxLength = 32767;
            this.yazar_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.yazar_txt.Modified = false;
            this.yazar_txt.Multiline = false;
            this.yazar_txt.Name = "yazar_txt";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.yazar_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnIdleState = stateProperties20;
            this.yazar_txt.Padding = new System.Windows.Forms.Padding(3);
            this.yazar_txt.PasswordChar = '\0';
            this.yazar_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.yazar_txt.PlaceholderText = "Yazar";
            this.yazar_txt.ReadOnly = false;
            this.yazar_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.yazar_txt.SelectedText = "";
            this.yazar_txt.SelectionLength = 0;
            this.yazar_txt.SelectionStart = 0;
            this.yazar_txt.ShortcutsEnabled = true;
            this.yazar_txt.Size = new System.Drawing.Size(244, 37);
            this.yazar_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.yazar_txt.TabIndex = 111;
            this.yazar_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.yazar_txt.TextMarginBottom = 0;
            this.yazar_txt.TextMarginLeft = 3;
            this.yazar_txt.TextMarginTop = 0;
            this.yazar_txt.TextPlaceholder = "Yazar";
            this.yazar_txt.UseSystemPasswordChar = false;
            this.yazar_txt.WordWrap = true;
            // 
            // İsim_txt
            // 
            this.İsim_txt.AcceptsReturn = false;
            this.İsim_txt.AcceptsTab = false;
            this.İsim_txt.AnimationSpeed = 200;
            this.İsim_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.İsim_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.İsim_txt.BackColor = System.Drawing.Color.Transparent;
            this.İsim_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("İsim_txt.BackgroundImage")));
            this.İsim_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.İsim_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.İsim_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.İsim_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.İsim_txt.BorderRadius = 1;
            this.İsim_txt.BorderThickness = 1;
            this.İsim_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.İsim_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.İsim_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.İsim_txt.DefaultText = "";
            this.İsim_txt.FillColor = System.Drawing.Color.White;
            this.İsim_txt.HideSelection = true;
            this.İsim_txt.IconLeft = null;
            this.İsim_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.İsim_txt.IconPadding = 10;
            this.İsim_txt.IconRight = null;
            this.İsim_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.İsim_txt.Lines = new string[0];
            this.İsim_txt.Location = new System.Drawing.Point(12, 12);
            this.İsim_txt.MaxLength = 32767;
            this.İsim_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.İsim_txt.Modified = false;
            this.İsim_txt.Multiline = false;
            this.İsim_txt.Name = "İsim_txt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.İsim_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.İsim_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.İsim_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.İsim_txt.OnIdleState = stateProperties24;
            this.İsim_txt.Padding = new System.Windows.Forms.Padding(3);
            this.İsim_txt.PasswordChar = '\0';
            this.İsim_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.İsim_txt.PlaceholderText = "Kitap İsim";
            this.İsim_txt.ReadOnly = false;
            this.İsim_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.İsim_txt.SelectedText = "";
            this.İsim_txt.SelectionLength = 0;
            this.İsim_txt.SelectionStart = 0;
            this.İsim_txt.ShortcutsEnabled = true;
            this.İsim_txt.Size = new System.Drawing.Size(244, 37);
            this.İsim_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.İsim_txt.TabIndex = 110;
            this.İsim_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.İsim_txt.TextMarginBottom = 0;
            this.İsim_txt.TextMarginLeft = 3;
            this.İsim_txt.TextMarginTop = 0;
            this.İsim_txt.TextPlaceholder = "Kitap İsim";
            this.İsim_txt.UseSystemPasswordChar = false;
            this.İsim_txt.WordWrap = true;
            // 
            // EgitimBtn
            // 
            this.EgitimBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(134)))), ((int)(((byte)(222)))));
            this.EgitimBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(134)))), ((int)(((byte)(222)))));
            this.EgitimBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.EgitimBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.EgitimBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.EgitimBtn.ForeColor = System.Drawing.Color.White;
            this.EgitimBtn.Image = ((System.Drawing.Image)(resources.GetObject("EgitimBtn.Image")));
            this.EgitimBtn.ImagePosition = 20;
            this.EgitimBtn.ImageZoom = 50;
            this.EgitimBtn.LabelPosition = 41;
            this.EgitimBtn.LabelText = "Eğitim";
            this.EgitimBtn.Location = new System.Drawing.Point(592, 134);
            this.EgitimBtn.Margin = new System.Windows.Forms.Padding(6);
            this.EgitimBtn.Name = "EgitimBtn";
            this.EgitimBtn.Size = new System.Drawing.Size(110, 110);
            this.EgitimBtn.TabIndex = 109;
            this.EgitimBtn.Click += new System.EventHandler(this.EgitimBtn_Click);
            // 
            // BilimBtn
            // 
            this.BilimBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(160)))), ((int)(((byte)(255)))));
            this.BilimBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(160)))), ((int)(((byte)(255)))));
            this.BilimBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.BilimBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BilimBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.BilimBtn.ForeColor = System.Drawing.Color.White;
            this.BilimBtn.Image = ((System.Drawing.Image)(resources.GetObject("BilimBtn.Image")));
            this.BilimBtn.ImagePosition = 10;
            this.BilimBtn.ImageZoom = 70;
            this.BilimBtn.LabelPosition = 41;
            this.BilimBtn.LabelText = "Bilim";
            this.BilimBtn.Location = new System.Drawing.Point(714, 378);
            this.BilimBtn.Margin = new System.Windows.Forms.Padding(6);
            this.BilimBtn.Name = "BilimBtn";
            this.BilimBtn.Size = new System.Drawing.Size(110, 110);
            this.BilimBtn.TabIndex = 108;
            this.BilimBtn.Click += new System.EventHandler(this.BilimBtn_Click);
            // 
            // TarihBtn
            // 
            this.TarihBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(211)))), ((int)(((byte)(84)))), ((int)(((byte)(0)))));
            this.TarihBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(211)))), ((int)(((byte)(84)))), ((int)(((byte)(0)))));
            this.TarihBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.TarihBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.TarihBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.TarihBtn.ForeColor = System.Drawing.Color.White;
            this.TarihBtn.Image = ((System.Drawing.Image)(resources.GetObject("TarihBtn.Image")));
            this.TarihBtn.ImagePosition = 10;
            this.TarihBtn.ImageZoom = 60;
            this.TarihBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.TarihBtn.LabelPosition = 41;
            this.TarihBtn.LabelText = "Tarih";
            this.TarihBtn.Location = new System.Drawing.Point(592, 377);
            this.TarihBtn.Margin = new System.Windows.Forms.Padding(6);
            this.TarihBtn.Name = "TarihBtn";
            this.TarihBtn.Size = new System.Drawing.Size(110, 110);
            this.TarihBtn.TabIndex = 107;
            this.TarihBtn.Click += new System.EventHandler(this.TarihBtn_Click);
            // 
            // TeknolojiBtn
            // 
            this.TeknolojiBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(20)))), ((int)(((byte)(100)))));
            this.TeknolojiBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(20)))), ((int)(((byte)(100)))));
            this.TeknolojiBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.TeknolojiBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.TeknolojiBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.TeknolojiBtn.ForeColor = System.Drawing.Color.White;
            this.TeknolojiBtn.Image = ((System.Drawing.Image)(resources.GetObject("TeknolojiBtn.Image")));
            this.TeknolojiBtn.ImagePosition = 10;
            this.TeknolojiBtn.ImageZoom = 60;
            this.TeknolojiBtn.LabelPosition = 41;
            this.TeknolojiBtn.LabelText = "Teknoloji";
            this.TeknolojiBtn.Location = new System.Drawing.Point(836, 256);
            this.TeknolojiBtn.Margin = new System.Windows.Forms.Padding(6);
            this.TeknolojiBtn.Name = "TeknolojiBtn";
            this.TeknolojiBtn.Size = new System.Drawing.Size(110, 110);
            this.TeknolojiBtn.TabIndex = 106;
            this.TeknolojiBtn.Click += new System.EventHandler(this.TeknolojiBtn_Click);
            // 
            // EdebiyatBtn
            // 
            this.EdebiyatBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.EdebiyatBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.EdebiyatBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.EdebiyatBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.EdebiyatBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.EdebiyatBtn.ForeColor = System.Drawing.Color.White;
            this.EdebiyatBtn.Image = ((System.Drawing.Image)(resources.GetObject("EdebiyatBtn.Image")));
            this.EdebiyatBtn.ImagePosition = 10;
            this.EdebiyatBtn.ImageZoom = 60;
            this.EdebiyatBtn.LabelPosition = 41;
            this.EdebiyatBtn.LabelText = "Edebiyat";
            this.EdebiyatBtn.Location = new System.Drawing.Point(833, 377);
            this.EdebiyatBtn.Margin = new System.Windows.Forms.Padding(6);
            this.EdebiyatBtn.Name = "EdebiyatBtn";
            this.EdebiyatBtn.Size = new System.Drawing.Size(110, 110);
            this.EdebiyatBtn.TabIndex = 105;
            this.EdebiyatBtn.Click += new System.EventHandler(this.EdebiyatBtn_Click);
            // 
            // SanatBtn
            // 
            this.SanatBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(188)))), ((int)(((byte)(156)))));
            this.SanatBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(188)))), ((int)(((byte)(156)))));
            this.SanatBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.SanatBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.SanatBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.SanatBtn.ForeColor = System.Drawing.Color.White;
            this.SanatBtn.Image = ((System.Drawing.Image)(resources.GetObject("SanatBtn.Image")));
            this.SanatBtn.ImagePosition = 15;
            this.SanatBtn.ImageZoom = 50;
            this.SanatBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.SanatBtn.LabelPosition = 41;
            this.SanatBtn.LabelText = "Sanat";
            this.SanatBtn.Location = new System.Drawing.Point(592, 256);
            this.SanatBtn.Margin = new System.Windows.Forms.Padding(6);
            this.SanatBtn.Name = "SanatBtn";
            this.SanatBtn.Size = new System.Drawing.Size(110, 110);
            this.SanatBtn.TabIndex = 104;
            this.SanatBtn.Click += new System.EventHandler(this.SanatBtn_Click);
            // 
            // AskBtn
            // 
            this.AskBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(68)))), ((int)(((byte)(173)))));
            this.AskBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(68)))), ((int)(((byte)(173)))));
            this.AskBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.AskBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.AskBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.AskBtn.ForeColor = System.Drawing.Color.White;
            this.AskBtn.Image = ((System.Drawing.Image)(resources.GetObject("AskBtn.Image")));
            this.AskBtn.ImagePosition = 10;
            this.AskBtn.ImageZoom = 70;
            this.AskBtn.LabelPosition = 41;
            this.AskBtn.LabelText = "Aşk";
            this.AskBtn.Location = new System.Drawing.Point(836, 134);
            this.AskBtn.Margin = new System.Windows.Forms.Padding(6);
            this.AskBtn.Name = "AskBtn";
            this.AskBtn.Size = new System.Drawing.Size(110, 110);
            this.AskBtn.TabIndex = 103;
            this.AskBtn.Click += new System.EventHandler(this.AskBtn_Click);
            // 
            // AksiyonBtn
            // 
            this.AksiyonBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(57)))), ((int)(((byte)(43)))));
            this.AksiyonBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(57)))), ((int)(((byte)(43)))));
            this.AksiyonBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.AksiyonBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.AksiyonBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.AksiyonBtn.ForeColor = System.Drawing.Color.White;
            this.AksiyonBtn.Image = ((System.Drawing.Image)(resources.GetObject("AksiyonBtn.Image")));
            this.AksiyonBtn.ImagePosition = 20;
            this.AksiyonBtn.ImageZoom = 50;
            this.AksiyonBtn.LabelPosition = 41;
            this.AksiyonBtn.LabelText = "Aksiyon";
            this.AksiyonBtn.Location = new System.Drawing.Point(714, 134);
            this.AksiyonBtn.Margin = new System.Windows.Forms.Padding(6);
            this.AksiyonBtn.Name = "AksiyonBtn";
            this.AksiyonBtn.Size = new System.Drawing.Size(110, 110);
            this.AksiyonBtn.TabIndex = 102;
            this.AksiyonBtn.Click += new System.EventHandler(this.AksiyonBtn_Click);
            // 
            // FelsefeBtn
            // 
            this.FelsefeBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(195)))), ((int)(((byte)(199)))));
            this.FelsefeBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(195)))), ((int)(((byte)(199)))));
            this.FelsefeBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.FelsefeBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.FelsefeBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.FelsefeBtn.ForeColor = System.Drawing.Color.White;
            this.FelsefeBtn.Image = ((System.Drawing.Image)(resources.GetObject("FelsefeBtn.Image")));
            this.FelsefeBtn.ImagePosition = 10;
            this.FelsefeBtn.ImageZoom = 50;
            this.FelsefeBtn.LabelPosition = 41;
            this.FelsefeBtn.LabelText = "Felsefe";
            this.FelsefeBtn.Location = new System.Drawing.Point(714, 256);
            this.FelsefeBtn.Margin = new System.Windows.Forms.Padding(6);
            this.FelsefeBtn.Name = "FelsefeBtn";
            this.FelsefeBtn.Size = new System.Drawing.Size(110, 110);
            this.FelsefeBtn.TabIndex = 101;
            this.FelsefeBtn.Click += new System.EventHandler(this.FelsefeBtn_Click);
            // 
            // BilimKurguBtn
            // 
            this.BilimKurguBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.BilimKurguBtn.color = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.BilimKurguBtn.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.BilimKurguBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BilimKurguBtn.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.BilimKurguBtn.ForeColor = System.Drawing.Color.White;
            this.BilimKurguBtn.Image = ((System.Drawing.Image)(resources.GetObject("BilimKurguBtn.Image")));
            this.BilimKurguBtn.ImagePosition = 20;
            this.BilimKurguBtn.ImageZoom = 50;
            this.BilimKurguBtn.LabelPosition = 41;
            this.BilimKurguBtn.LabelText = "Bilim-Kurgu";
            this.BilimKurguBtn.Location = new System.Drawing.Point(836, 12);
            this.BilimKurguBtn.Margin = new System.Windows.Forms.Padding(6);
            this.BilimKurguBtn.Name = "BilimKurguBtn";
            this.BilimKurguBtn.Size = new System.Drawing.Size(110, 110);
            this.BilimKurguBtn.TabIndex = 100;
            this.BilimKurguBtn.Click += new System.EventHandler(this.BilimKurguBtn_Click);
            // 
            // PolisiyeButton
            // 
            this.PolisiyeButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(128)))), ((int)(((byte)(185)))));
            this.PolisiyeButton.color = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(128)))), ((int)(((byte)(185)))));
            this.PolisiyeButton.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.PolisiyeButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.PolisiyeButton.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.PolisiyeButton.ForeColor = System.Drawing.Color.White;
            this.PolisiyeButton.Image = ((System.Drawing.Image)(resources.GetObject("PolisiyeButton.Image")));
            this.PolisiyeButton.ImagePosition = 10;
            this.PolisiyeButton.ImageZoom = 70;
            this.PolisiyeButton.LabelPosition = 41;
            this.PolisiyeButton.LabelText = "Polisiye";
            this.PolisiyeButton.Location = new System.Drawing.Point(714, 12);
            this.PolisiyeButton.Margin = new System.Windows.Forms.Padding(6);
            this.PolisiyeButton.Name = "PolisiyeButton";
            this.PolisiyeButton.Size = new System.Drawing.Size(110, 110);
            this.PolisiyeButton.TabIndex = 99;
            this.PolisiyeButton.Click += new System.EventHandler(this.PolisiyeButton_Click);
            // 
            // fantastikButton
            // 
            this.fantastikButton.BackColor = System.Drawing.Color.SeaGreen;
            this.fantastikButton.color = System.Drawing.Color.SeaGreen;
            this.fantastikButton.colorActive = System.Drawing.Color.MediumSeaGreen;
            this.fantastikButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.fantastikButton.Font = new System.Drawing.Font("Century Gothic", 15.75F);
            this.fantastikButton.ForeColor = System.Drawing.Color.White;
            this.fantastikButton.Image = ((System.Drawing.Image)(resources.GetObject("fantastikButton.Image")));
            this.fantastikButton.ImagePosition = 5;
            this.fantastikButton.ImageZoom = 60;
            this.fantastikButton.LabelPosition = 41;
            this.fantastikButton.LabelText = "Fantastik";
            this.fantastikButton.Location = new System.Drawing.Point(592, 12);
            this.fantastikButton.Margin = new System.Windows.Forms.Padding(6);
            this.fantastikButton.Name = "fantastikButton";
            this.fantastikButton.Size = new System.Drawing.Size(110, 110);
            this.fantastikButton.TabIndex = 98;
            this.fantastikButton.Click += new System.EventHandler(this.fantastikButton_Click);
            // 
            // kitaplikDataGridView
            // 
            this.kitaplikDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.kitaplikDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.kitaplikDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.kitaplikDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.kitaplikDataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.kitaplikDataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.kitaplikDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.kitaplikDataGridView.ColumnHeadersHeight = 40;
            this.kitaplikDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.kitaplikDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.kitaplikDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.kitaplikDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.kitaplikDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.kitaplikDataGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.kitaplikDataGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.kitaplikDataGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.kitaplikDataGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.kitaplikDataGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.kitaplikDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.kitaplikDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.kitaplikDataGridView.CurrentTheme.Name = null;
            this.kitaplikDataGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.kitaplikDataGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.kitaplikDataGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.kitaplikDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.kitaplikDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.kitaplikDataGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.kitaplikDataGridView.EnableHeadersVisualStyles = false;
            this.kitaplikDataGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.kitaplikDataGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.kitaplikDataGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.kitaplikDataGridView.HeaderForeColor = System.Drawing.Color.White;
            this.kitaplikDataGridView.Location = new System.Drawing.Point(12, 227);
            this.kitaplikDataGridView.Name = "kitaplikDataGridView";
            this.kitaplikDataGridView.RowHeadersVisible = false;
            this.kitaplikDataGridView.RowHeadersWidth = 62;
            this.kitaplikDataGridView.RowTemplate.Height = 40;
            this.kitaplikDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.kitaplikDataGridView.Size = new System.Drawing.Size(563, 354);
            this.kitaplikDataGridView.TabIndex = 97;
            this.kitaplikDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.kitaplikDataGridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.kitaplikDataGridView_CellClick);
            // 
            // AraBtn
            // 
            this.AraBtn.AllowAnimations = true;
            this.AraBtn.AllowMouseEffects = true;
            this.AraBtn.AllowToggling = false;
            this.AraBtn.AnimationSpeed = 200;
            this.AraBtn.AutoGenerateColors = false;
            this.AraBtn.AutoRoundBorders = false;
            this.AraBtn.AutoSizeLeftIcon = true;
            this.AraBtn.AutoSizeRightIcon = true;
            this.AraBtn.BackColor = System.Drawing.Color.Transparent;
            this.AraBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.AraBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AraBtn.BackgroundImage")));
            this.AraBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.ButtonText = "Ara";
            this.AraBtn.ButtonTextMarginLeft = 0;
            this.AraBtn.ColorContrastOnClick = 45;
            this.AraBtn.ColorContrastOnHover = 45;
            this.AraBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AraBtn.CustomizableEdges = borderEdges2;
            this.AraBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AraBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AraBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AraBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AraBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AraBtn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.AraBtn.ForeColor = System.Drawing.Color.White;
            this.AraBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AraBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AraBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AraBtn.IconMarginLeft = 11;
            this.AraBtn.IconPadding = 10;
            this.AraBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AraBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AraBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AraBtn.IconSize = 25;
            this.AraBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.IdleBorderRadius = 1;
            this.AraBtn.IdleBorderThickness = 1;
            this.AraBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.IdleIconLeftImage = null;
            this.AraBtn.IdleIconRightImage = null;
            this.AraBtn.IndicateFocus = false;
            this.AraBtn.Location = new System.Drawing.Point(592, 539);
            this.AraBtn.Name = "AraBtn";
            this.AraBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AraBtn.OnDisabledState.BorderRadius = 1;
            this.AraBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnDisabledState.BorderThickness = 1;
            this.AraBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AraBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AraBtn.OnDisabledState.IconLeftImage = null;
            this.AraBtn.OnDisabledState.IconRightImage = null;
            this.AraBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AraBtn.onHoverState.BorderRadius = 1;
            this.AraBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.onHoverState.BorderThickness = 1;
            this.AraBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AraBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.onHoverState.IconLeftImage = null;
            this.AraBtn.onHoverState.IconRightImage = null;
            this.AraBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.OnIdleState.BorderRadius = 1;
            this.AraBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnIdleState.BorderThickness = 1;
            this.AraBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.OnIdleState.IconLeftImage = null;
            this.AraBtn.OnIdleState.IconRightImage = null;
            this.AraBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AraBtn.OnPressedState.BorderRadius = 1;
            this.AraBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnPressedState.BorderThickness = 1;
            this.AraBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AraBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.OnPressedState.IconLeftImage = null;
            this.AraBtn.OnPressedState.IconRightImage = null;
            this.AraBtn.Size = new System.Drawing.Size(172, 37);
            this.AraBtn.TabIndex = 96;
            this.AraBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AraBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AraBtn.TextMarginLeft = 0;
            this.AraBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AraBtn.UseDefaultRadiusAndThickness = true;
            this.AraBtn.Click += new System.EventHandler(this.AraBtn_Click);
            // 
            // kitapAra_txt
            // 
            this.kitapAra_txt.AcceptsReturn = false;
            this.kitapAra_txt.AcceptsTab = false;
            this.kitapAra_txt.AnimationSpeed = 200;
            this.kitapAra_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.kitapAra_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.kitapAra_txt.BackColor = System.Drawing.Color.Transparent;
            this.kitapAra_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("kitapAra_txt.BackgroundImage")));
            this.kitapAra_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.kitapAra_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.kitapAra_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.kitapAra_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.kitapAra_txt.BorderRadius = 1;
            this.kitapAra_txt.BorderThickness = 1;
            this.kitapAra_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.kitapAra_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.kitapAra_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.kitapAra_txt.DefaultText = "";
            this.kitapAra_txt.FillColor = System.Drawing.Color.White;
            this.kitapAra_txt.HideSelection = true;
            this.kitapAra_txt.IconLeft = null;
            this.kitapAra_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.kitapAra_txt.IconPadding = 10;
            this.kitapAra_txt.IconRight = null;
            this.kitapAra_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.kitapAra_txt.Lines = new string[0];
            this.kitapAra_txt.Location = new System.Drawing.Point(592, 496);
            this.kitapAra_txt.MaxLength = 32767;
            this.kitapAra_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.kitapAra_txt.Modified = false;
            this.kitapAra_txt.Multiline = false;
            this.kitapAra_txt.Name = "kitapAra_txt";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kitapAra_txt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.kitapAra_txt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kitapAra_txt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kitapAra_txt.OnIdleState = stateProperties28;
            this.kitapAra_txt.Padding = new System.Windows.Forms.Padding(3);
            this.kitapAra_txt.PasswordChar = '\0';
            this.kitapAra_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.kitapAra_txt.PlaceholderText = "Kitap Ara";
            this.kitapAra_txt.ReadOnly = false;
            this.kitapAra_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.kitapAra_txt.SelectedText = "";
            this.kitapAra_txt.SelectionLength = 0;
            this.kitapAra_txt.SelectionStart = 0;
            this.kitapAra_txt.ShortcutsEnabled = true;
            this.kitapAra_txt.Size = new System.Drawing.Size(351, 37);
            this.kitapAra_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.kitapAra_txt.TabIndex = 94;
            this.kitapAra_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.kitapAra_txt.TextMarginBottom = 0;
            this.kitapAra_txt.TextMarginLeft = 3;
            this.kitapAra_txt.TextMarginTop = 0;
            this.kitapAra_txt.TextPlaceholder = "Kitap Ara";
            this.kitapAra_txt.UseSystemPasswordChar = false;
            this.kitapAra_txt.WordWrap = true;
            // 
            // baski_txt
            // 
            this.baski_txt.AcceptsReturn = false;
            this.baski_txt.AcceptsTab = false;
            this.baski_txt.AnimationSpeed = 200;
            this.baski_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.baski_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.baski_txt.BackColor = System.Drawing.Color.Transparent;
            this.baski_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("baski_txt.BackgroundImage")));
            this.baski_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.baski_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.baski_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.baski_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.baski_txt.BorderRadius = 1;
            this.baski_txt.BorderThickness = 1;
            this.baski_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.baski_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.baski_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.baski_txt.DefaultText = "";
            this.baski_txt.FillColor = System.Drawing.Color.White;
            this.baski_txt.HideSelection = true;
            this.baski_txt.IconLeft = null;
            this.baski_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.baski_txt.IconPadding = 10;
            this.baski_txt.IconRight = null;
            this.baski_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.baski_txt.Lines = new string[0];
            this.baski_txt.Location = new System.Drawing.Point(262, 98);
            this.baski_txt.MaxLength = 32767;
            this.baski_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.baski_txt.Modified = false;
            this.baski_txt.Multiline = false;
            this.baski_txt.Name = "baski_txt";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.baski_txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.baski_txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.baski_txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.baski_txt.OnIdleState = stateProperties32;
            this.baski_txt.Padding = new System.Windows.Forms.Padding(3);
            this.baski_txt.PasswordChar = '\0';
            this.baski_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.baski_txt.PlaceholderText = "Baskı";
            this.baski_txt.ReadOnly = false;
            this.baski_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.baski_txt.SelectedText = "";
            this.baski_txt.SelectionLength = 0;
            this.baski_txt.SelectionStart = 0;
            this.baski_txt.ShortcutsEnabled = true;
            this.baski_txt.Size = new System.Drawing.Size(180, 37);
            this.baski_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.baski_txt.TabIndex = 118;
            this.baski_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.baski_txt.TextMarginBottom = 0;
            this.baski_txt.TextMarginLeft = 3;
            this.baski_txt.TextMarginTop = 0;
            this.baski_txt.TextPlaceholder = "Baskı";
            this.baski_txt.UseSystemPasswordChar = false;
            this.baski_txt.WordWrap = true;
            // 
            // UyeKitaplık
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(958, 591);
            this.Controls.Add(this.baski_txt);
            this.Controls.Add(this.TemizleBtn);
            this.Controls.Add(this.sayfa_txt);
            this.Controls.Add(this.dil_txt);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.ozet_txt);
            this.Controls.Add(this.tur_txt);
            this.Controls.Add(this.yazar_txt);
            this.Controls.Add(this.İsim_txt);
            this.Controls.Add(this.EgitimBtn);
            this.Controls.Add(this.BilimBtn);
            this.Controls.Add(this.TarihBtn);
            this.Controls.Add(this.TeknolojiBtn);
            this.Controls.Add(this.EdebiyatBtn);
            this.Controls.Add(this.SanatBtn);
            this.Controls.Add(this.AskBtn);
            this.Controls.Add(this.AksiyonBtn);
            this.Controls.Add(this.FelsefeBtn);
            this.Controls.Add(this.BilimKurguBtn);
            this.Controls.Add(this.PolisiyeButton);
            this.Controls.Add(this.fantastikButton);
            this.Controls.Add(this.kitaplikDataGridView);
            this.Controls.Add(this.AraBtn);
            this.Controls.Add(this.kitapAra_txt);
            this.Name = "UyeKitaplık";
            this.Text = "Kitaplık";
            this.Load += new System.EventHandler(this.UyeKitaplık_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kitaplikDataGridView)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton TemizleBtn;
        private Bunifu.UI.WinForms.BunifuTextBox sayfa_txt;
        private Bunifu.UI.WinForms.BunifuTextBox dil_txt;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuTextBox ozet_txt;
        private Bunifu.UI.WinForms.BunifuTextBox tur_txt;
        private Bunifu.UI.WinForms.BunifuTextBox yazar_txt;
        private Bunifu.UI.WinForms.BunifuTextBox İsim_txt;
        private Bunifu.Framework.UI.BunifuTileButton EgitimBtn;
        private Bunifu.Framework.UI.BunifuTileButton BilimBtn;
        private Bunifu.Framework.UI.BunifuTileButton TarihBtn;
        private Bunifu.Framework.UI.BunifuTileButton TeknolojiBtn;
        private Bunifu.Framework.UI.BunifuTileButton EdebiyatBtn;
        private Bunifu.Framework.UI.BunifuTileButton SanatBtn;
        private Bunifu.Framework.UI.BunifuTileButton AskBtn;
        private Bunifu.Framework.UI.BunifuTileButton AksiyonBtn;
        private Bunifu.Framework.UI.BunifuTileButton FelsefeBtn;
        private Bunifu.Framework.UI.BunifuTileButton BilimKurguBtn;
        private Bunifu.Framework.UI.BunifuTileButton PolisiyeButton;
        private Bunifu.Framework.UI.BunifuTileButton fantastikButton;
        private Bunifu.UI.WinForms.BunifuDataGridView kitaplikDataGridView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AraBtn;
        private Bunifu.UI.WinForms.BunifuTextBox kitapAra_txt;
        private Bunifu.UI.WinForms.BunifuTextBox baski_txt;
    }
}