
namespace SMARTLİBRARY
{
    partial class Kitaplar
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Kitaplar));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.kimlik_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.telefon_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.adres_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.adsoyad_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ozet_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tur_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.yazar_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.kitapİsim_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UyeResimBox = new System.Windows.Forms.PictureBox();
            this.oduncDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.araBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ara_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.temizle_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.UyeResimBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.oduncDataGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // kimlik_txt
            // 
            this.kimlik_txt.AcceptsReturn = false;
            this.kimlik_txt.AcceptsTab = false;
            this.kimlik_txt.AnimationSpeed = 200;
            this.kimlik_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.kimlik_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.kimlik_txt.BackColor = System.Drawing.Color.Transparent;
            this.kimlik_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("kimlik_txt.BackgroundImage")));
            this.kimlik_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.kimlik_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.kimlik_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.kimlik_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.kimlik_txt.BorderRadius = 1;
            this.kimlik_txt.BorderThickness = 1;
            this.kimlik_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.kimlik_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.kimlik_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.kimlik_txt.DefaultText = "";
            this.kimlik_txt.FillColor = System.Drawing.Color.White;
            this.kimlik_txt.HideSelection = true;
            this.kimlik_txt.IconLeft = null;
            this.kimlik_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.kimlik_txt.IconPadding = 10;
            this.kimlik_txt.IconRight = null;
            this.kimlik_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.kimlik_txt.Lines = new string[0];
            this.kimlik_txt.Location = new System.Drawing.Point(18, 217);
            this.kimlik_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.kimlik_txt.MaxLength = 32767;
            this.kimlik_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.kimlik_txt.Modified = false;
            this.kimlik_txt.Multiline = false;
            this.kimlik_txt.Name = "kimlik_txt";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kimlik_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.kimlik_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kimlik_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kimlik_txt.OnIdleState = stateProperties4;
            this.kimlik_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.kimlik_txt.PasswordChar = '\0';
            this.kimlik_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.kimlik_txt.PlaceholderText = "Kimlik";
            this.kimlik_txt.ReadOnly = false;
            this.kimlik_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.kimlik_txt.SelectedText = "";
            this.kimlik_txt.SelectionLength = 0;
            this.kimlik_txt.SelectionStart = 0;
            this.kimlik_txt.ShortcutsEnabled = true;
            this.kimlik_txt.Size = new System.Drawing.Size(390, 57);
            this.kimlik_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.kimlik_txt.TabIndex = 24;
            this.kimlik_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.kimlik_txt.TextMarginBottom = 0;
            this.kimlik_txt.TextMarginLeft = 3;
            this.kimlik_txt.TextMarginTop = 0;
            this.kimlik_txt.TextPlaceholder = "Kimlik";
            this.kimlik_txt.UseSystemPasswordChar = false;
            this.kimlik_txt.WordWrap = true;
            // 
            // telefon_txt
            // 
            this.telefon_txt.AcceptsReturn = false;
            this.telefon_txt.AcceptsTab = false;
            this.telefon_txt.AnimationSpeed = 200;
            this.telefon_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.telefon_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.telefon_txt.BackColor = System.Drawing.Color.Transparent;
            this.telefon_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("telefon_txt.BackgroundImage")));
            this.telefon_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.telefon_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.telefon_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.telefon_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.telefon_txt.BorderRadius = 1;
            this.telefon_txt.BorderThickness = 1;
            this.telefon_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.telefon_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.telefon_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.telefon_txt.DefaultText = "";
            this.telefon_txt.FillColor = System.Drawing.Color.White;
            this.telefon_txt.HideSelection = true;
            this.telefon_txt.IconLeft = null;
            this.telefon_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.telefon_txt.IconPadding = 10;
            this.telefon_txt.IconRight = null;
            this.telefon_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.telefon_txt.Lines = new string[0];
            this.telefon_txt.Location = new System.Drawing.Point(18, 151);
            this.telefon_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.telefon_txt.MaxLength = 32767;
            this.telefon_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.telefon_txt.Modified = false;
            this.telefon_txt.Multiline = false;
            this.telefon_txt.Name = "telefon_txt";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telefon_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.telefon_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telefon_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.telefon_txt.OnIdleState = stateProperties8;
            this.telefon_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.telefon_txt.PasswordChar = '\0';
            this.telefon_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.telefon_txt.PlaceholderText = "Telefon";
            this.telefon_txt.ReadOnly = false;
            this.telefon_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.telefon_txt.SelectedText = "";
            this.telefon_txt.SelectionLength = 0;
            this.telefon_txt.SelectionStart = 0;
            this.telefon_txt.ShortcutsEnabled = true;
            this.telefon_txt.Size = new System.Drawing.Size(390, 57);
            this.telefon_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.telefon_txt.TabIndex = 23;
            this.telefon_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.telefon_txt.TextMarginBottom = 0;
            this.telefon_txt.TextMarginLeft = 3;
            this.telefon_txt.TextMarginTop = 0;
            this.telefon_txt.TextPlaceholder = "Telefon";
            this.telefon_txt.UseSystemPasswordChar = false;
            this.telefon_txt.WordWrap = true;
            this.telefon_txt.TextChanged += new System.EventHandler(this.bunifuTextBox2_TextChanged);
            // 
            // adres_txt
            // 
            this.adres_txt.AcceptsReturn = false;
            this.adres_txt.AcceptsTab = false;
            this.adres_txt.AnimationSpeed = 200;
            this.adres_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.adres_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.adres_txt.BackColor = System.Drawing.Color.Transparent;
            this.adres_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adres_txt.BackgroundImage")));
            this.adres_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.adres_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adres_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.adres_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.adres_txt.BorderRadius = 1;
            this.adres_txt.BorderThickness = 1;
            this.adres_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.adres_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.adres_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.adres_txt.DefaultText = "";
            this.adres_txt.FillColor = System.Drawing.Color.White;
            this.adres_txt.HideSelection = true;
            this.adres_txt.IconLeft = null;
            this.adres_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.adres_txt.IconPadding = 10;
            this.adres_txt.IconRight = null;
            this.adres_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.adres_txt.Lines = new string[0];
            this.adres_txt.Location = new System.Drawing.Point(18, 85);
            this.adres_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.adres_txt.MaxLength = 32767;
            this.adres_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.adres_txt.Modified = false;
            this.adres_txt.Multiline = false;
            this.adres_txt.Name = "adres_txt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adres_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.adres_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adres_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adres_txt.OnIdleState = stateProperties12;
            this.adres_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.adres_txt.PasswordChar = '\0';
            this.adres_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.adres_txt.PlaceholderText = "Adres";
            this.adres_txt.ReadOnly = false;
            this.adres_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.adres_txt.SelectedText = "";
            this.adres_txt.SelectionLength = 0;
            this.adres_txt.SelectionStart = 0;
            this.adres_txt.ShortcutsEnabled = true;
            this.adres_txt.Size = new System.Drawing.Size(390, 57);
            this.adres_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.adres_txt.TabIndex = 22;
            this.adres_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.adres_txt.TextMarginBottom = 0;
            this.adres_txt.TextMarginLeft = 3;
            this.adres_txt.TextMarginTop = 0;
            this.adres_txt.TextPlaceholder = "Adres";
            this.adres_txt.UseSystemPasswordChar = false;
            this.adres_txt.WordWrap = true;
            // 
            // adsoyad_txt
            // 
            this.adsoyad_txt.AcceptsReturn = false;
            this.adsoyad_txt.AcceptsTab = false;
            this.adsoyad_txt.AnimationSpeed = 200;
            this.adsoyad_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.adsoyad_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.adsoyad_txt.BackColor = System.Drawing.Color.Transparent;
            this.adsoyad_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adsoyad_txt.BackgroundImage")));
            this.adsoyad_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.adsoyad_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adsoyad_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.adsoyad_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.adsoyad_txt.BorderRadius = 1;
            this.adsoyad_txt.BorderThickness = 1;
            this.adsoyad_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.adsoyad_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.adsoyad_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.adsoyad_txt.DefaultText = "";
            this.adsoyad_txt.FillColor = System.Drawing.Color.White;
            this.adsoyad_txt.HideSelection = true;
            this.adsoyad_txt.IconLeft = null;
            this.adsoyad_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.adsoyad_txt.IconPadding = 10;
            this.adsoyad_txt.IconRight = null;
            this.adsoyad_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.adsoyad_txt.Lines = new string[0];
            this.adsoyad_txt.Location = new System.Drawing.Point(18, 18);
            this.adsoyad_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.adsoyad_txt.MaxLength = 32767;
            this.adsoyad_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.adsoyad_txt.Modified = false;
            this.adsoyad_txt.Multiline = false;
            this.adsoyad_txt.Name = "adsoyad_txt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adsoyad_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.adsoyad_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adsoyad_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adsoyad_txt.OnIdleState = stateProperties16;
            this.adsoyad_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.adsoyad_txt.PasswordChar = '\0';
            this.adsoyad_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.adsoyad_txt.PlaceholderText = "Ad Soyad";
            this.adsoyad_txt.ReadOnly = false;
            this.adsoyad_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.adsoyad_txt.SelectedText = "";
            this.adsoyad_txt.SelectionLength = 0;
            this.adsoyad_txt.SelectionStart = 0;
            this.adsoyad_txt.ShortcutsEnabled = true;
            this.adsoyad_txt.Size = new System.Drawing.Size(390, 57);
            this.adsoyad_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.adsoyad_txt.TabIndex = 21;
            this.adsoyad_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.adsoyad_txt.TextMarginBottom = 0;
            this.adsoyad_txt.TextMarginLeft = 3;
            this.adsoyad_txt.TextMarginTop = 0;
            this.adsoyad_txt.TextPlaceholder = "Ad Soyad";
            this.adsoyad_txt.UseSystemPasswordChar = false;
            this.adsoyad_txt.WordWrap = true;
            // 
            // ozet_txt
            // 
            this.ozet_txt.AcceptsReturn = false;
            this.ozet_txt.AcceptsTab = false;
            this.ozet_txt.AnimationSpeed = 200;
            this.ozet_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ozet_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ozet_txt.BackColor = System.Drawing.Color.Transparent;
            this.ozet_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ozet_txt.BackgroundImage")));
            this.ozet_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ozet_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ozet_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ozet_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ozet_txt.BorderRadius = 1;
            this.ozet_txt.BorderThickness = 1;
            this.ozet_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ozet_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ozet_txt.DefaultText = "";
            this.ozet_txt.FillColor = System.Drawing.Color.White;
            this.ozet_txt.HideSelection = true;
            this.ozet_txt.IconLeft = null;
            this.ozet_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.IconPadding = 10;
            this.ozet_txt.IconRight = null;
            this.ozet_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.Lines = new string[0];
            this.ozet_txt.Location = new System.Drawing.Point(417, 368);
            this.ozet_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ozet_txt.MaxLength = 32767;
            this.ozet_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.ozet_txt.Modified = false;
            this.ozet_txt.Multiline = false;
            this.ozet_txt.Name = "ozet_txt";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ozet_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnIdleState = stateProperties20;
            this.ozet_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ozet_txt.PasswordChar = '\0';
            this.ozet_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ozet_txt.PlaceholderText = "Özet";
            this.ozet_txt.ReadOnly = false;
            this.ozet_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ozet_txt.SelectedText = "";
            this.ozet_txt.SelectionLength = 0;
            this.ozet_txt.SelectionStart = 0;
            this.ozet_txt.ShortcutsEnabled = true;
            this.ozet_txt.Size = new System.Drawing.Size(252, 57);
            this.ozet_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ozet_txt.TabIndex = 28;
            this.ozet_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ozet_txt.TextMarginBottom = 0;
            this.ozet_txt.TextMarginLeft = 3;
            this.ozet_txt.TextMarginTop = 0;
            this.ozet_txt.TextPlaceholder = "Özet";
            this.ozet_txt.UseSystemPasswordChar = false;
            this.ozet_txt.WordWrap = true;
            // 
            // tur_txt
            // 
            this.tur_txt.AcceptsReturn = false;
            this.tur_txt.AcceptsTab = false;
            this.tur_txt.AnimationSpeed = 200;
            this.tur_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tur_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tur_txt.BackColor = System.Drawing.Color.Transparent;
            this.tur_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tur_txt.BackgroundImage")));
            this.tur_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tur_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tur_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tur_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.tur_txt.BorderRadius = 1;
            this.tur_txt.BorderThickness = 1;
            this.tur_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tur_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tur_txt.DefaultText = "";
            this.tur_txt.FillColor = System.Drawing.Color.White;
            this.tur_txt.HideSelection = true;
            this.tur_txt.IconLeft = null;
            this.tur_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.IconPadding = 10;
            this.tur_txt.IconRight = null;
            this.tur_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.Lines = new string[0];
            this.tur_txt.Location = new System.Drawing.Point(18, 368);
            this.tur_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tur_txt.MaxLength = 32767;
            this.tur_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.tur_txt.Modified = false;
            this.tur_txt.Multiline = false;
            this.tur_txt.Name = "tur_txt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tur_txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnIdleState = stateProperties24;
            this.tur_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tur_txt.PasswordChar = '\0';
            this.tur_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.tur_txt.PlaceholderText = "Tür";
            this.tur_txt.ReadOnly = false;
            this.tur_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tur_txt.SelectedText = "";
            this.tur_txt.SelectionLength = 0;
            this.tur_txt.SelectionStart = 0;
            this.tur_txt.ShortcutsEnabled = true;
            this.tur_txt.Size = new System.Drawing.Size(390, 57);
            this.tur_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tur_txt.TabIndex = 27;
            this.tur_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tur_txt.TextMarginBottom = 0;
            this.tur_txt.TextMarginLeft = 3;
            this.tur_txt.TextMarginTop = 0;
            this.tur_txt.TextPlaceholder = "Tür";
            this.tur_txt.UseSystemPasswordChar = false;
            this.tur_txt.WordWrap = true;
            // 
            // yazar_txt
            // 
            this.yazar_txt.AcceptsReturn = false;
            this.yazar_txt.AcceptsTab = false;
            this.yazar_txt.AnimationSpeed = 200;
            this.yazar_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.yazar_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.yazar_txt.BackColor = System.Drawing.Color.Transparent;
            this.yazar_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("yazar_txt.BackgroundImage")));
            this.yazar_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.yazar_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.yazar_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.yazar_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.yazar_txt.BorderRadius = 1;
            this.yazar_txt.BorderThickness = 1;
            this.yazar_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.yazar_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.yazar_txt.DefaultText = "";
            this.yazar_txt.FillColor = System.Drawing.Color.White;
            this.yazar_txt.HideSelection = true;
            this.yazar_txt.IconLeft = null;
            this.yazar_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.IconPadding = 10;
            this.yazar_txt.IconRight = null;
            this.yazar_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.Lines = new string[0];
            this.yazar_txt.Location = new System.Drawing.Point(417, 302);
            this.yazar_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.yazar_txt.MaxLength = 32767;
            this.yazar_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.yazar_txt.Modified = false;
            this.yazar_txt.Multiline = false;
            this.yazar_txt.Name = "yazar_txt";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.yazar_txt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnIdleState = stateProperties28;
            this.yazar_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.yazar_txt.PasswordChar = '\0';
            this.yazar_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.yazar_txt.PlaceholderText = "Yazar";
            this.yazar_txt.ReadOnly = false;
            this.yazar_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.yazar_txt.SelectedText = "";
            this.yazar_txt.SelectionLength = 0;
            this.yazar_txt.SelectionStart = 0;
            this.yazar_txt.ShortcutsEnabled = true;
            this.yazar_txt.Size = new System.Drawing.Size(252, 57);
            this.yazar_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.yazar_txt.TabIndex = 26;
            this.yazar_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.yazar_txt.TextMarginBottom = 0;
            this.yazar_txt.TextMarginLeft = 3;
            this.yazar_txt.TextMarginTop = 0;
            this.yazar_txt.TextPlaceholder = "Yazar";
            this.yazar_txt.UseSystemPasswordChar = false;
            this.yazar_txt.WordWrap = true;
            // 
            // kitapİsim_txt
            // 
            this.kitapİsim_txt.AcceptsReturn = false;
            this.kitapİsim_txt.AcceptsTab = false;
            this.kitapİsim_txt.AnimationSpeed = 200;
            this.kitapİsim_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.kitapİsim_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.kitapİsim_txt.BackColor = System.Drawing.Color.Transparent;
            this.kitapİsim_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("kitapİsim_txt.BackgroundImage")));
            this.kitapİsim_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.kitapİsim_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.kitapİsim_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.kitapİsim_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.kitapİsim_txt.BorderRadius = 1;
            this.kitapİsim_txt.BorderThickness = 1;
            this.kitapİsim_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.kitapİsim_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.kitapİsim_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.kitapİsim_txt.DefaultText = "";
            this.kitapİsim_txt.FillColor = System.Drawing.Color.White;
            this.kitapİsim_txt.HideSelection = true;
            this.kitapİsim_txt.IconLeft = null;
            this.kitapİsim_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.kitapİsim_txt.IconPadding = 10;
            this.kitapİsim_txt.IconRight = null;
            this.kitapİsim_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.kitapİsim_txt.Lines = new string[0];
            this.kitapİsim_txt.Location = new System.Drawing.Point(18, 302);
            this.kitapİsim_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.kitapİsim_txt.MaxLength = 32767;
            this.kitapİsim_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.kitapİsim_txt.Modified = false;
            this.kitapİsim_txt.Multiline = false;
            this.kitapİsim_txt.Name = "kitapİsim_txt";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kitapİsim_txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.kitapİsim_txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kitapİsim_txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.kitapİsim_txt.OnIdleState = stateProperties32;
            this.kitapİsim_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.kitapİsim_txt.PasswordChar = '\0';
            this.kitapİsim_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.kitapİsim_txt.PlaceholderText = "Kitap İsim";
            this.kitapİsim_txt.ReadOnly = false;
            this.kitapİsim_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.kitapİsim_txt.SelectedText = "";
            this.kitapİsim_txt.SelectionLength = 0;
            this.kitapİsim_txt.SelectionStart = 0;
            this.kitapİsim_txt.ShortcutsEnabled = true;
            this.kitapİsim_txt.Size = new System.Drawing.Size(390, 57);
            this.kitapİsim_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.kitapİsim_txt.TabIndex = 25;
            this.kitapİsim_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.kitapİsim_txt.TextMarginBottom = 0;
            this.kitapİsim_txt.TextMarginLeft = 3;
            this.kitapİsim_txt.TextMarginTop = 0;
            this.kitapİsim_txt.TextPlaceholder = "Kitap İsim";
            this.kitapİsim_txt.UseSystemPasswordChar = false;
            this.kitapİsim_txt.WordWrap = true;
            // 
            // UyeResimBox
            // 
            this.UyeResimBox.Image = ((System.Drawing.Image)(resources.GetObject("UyeResimBox.Image")));
            this.UyeResimBox.Location = new System.Drawing.Point(417, 18);
            this.UyeResimBox.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.UyeResimBox.Name = "UyeResimBox";
            this.UyeResimBox.Size = new System.Drawing.Size(252, 255);
            this.UyeResimBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.UyeResimBox.TabIndex = 31;
            this.UyeResimBox.TabStop = false;
            // 
            // oduncDataGridView
            // 
            this.oduncDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.oduncDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.oduncDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.oduncDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.oduncDataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.oduncDataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.oduncDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.oduncDataGridView.ColumnHeadersHeight = 40;
            this.oduncDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.oduncDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.oduncDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.oduncDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.oduncDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.oduncDataGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.oduncDataGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.oduncDataGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.oduncDataGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.oduncDataGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.oduncDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.oduncDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.oduncDataGridView.CurrentTheme.Name = null;
            this.oduncDataGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.oduncDataGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.oduncDataGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.oduncDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.oduncDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.oduncDataGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.oduncDataGridView.EnableHeadersVisualStyles = false;
            this.oduncDataGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.oduncDataGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.oduncDataGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.oduncDataGridView.HeaderForeColor = System.Drawing.Color.White;
            this.oduncDataGridView.Location = new System.Drawing.Point(18, 566);
            this.oduncDataGridView.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.oduncDataGridView.Name = "oduncDataGridView";
            this.oduncDataGridView.RowHeadersVisible = false;
            this.oduncDataGridView.RowHeadersWidth = 62;
            this.oduncDataGridView.RowTemplate.Height = 40;
            this.oduncDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.oduncDataGridView.Size = new System.Drawing.Size(1450, 557);
            this.oduncDataGridView.TabIndex = 32;
            this.oduncDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.oduncDataGridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.oduncDataGridView_CellClick);
            // 
            // araBtn
            // 
            this.araBtn.AllowAnimations = true;
            this.araBtn.AllowMouseEffects = true;
            this.araBtn.AllowToggling = false;
            this.araBtn.AnimationSpeed = 200;
            this.araBtn.AutoGenerateColors = false;
            this.araBtn.AutoRoundBorders = false;
            this.araBtn.AutoSizeLeftIcon = true;
            this.araBtn.AutoSizeRightIcon = true;
            this.araBtn.BackColor = System.Drawing.Color.Transparent;
            this.araBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.araBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("araBtn.BackgroundImage")));
            this.araBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.araBtn.ButtonText = "Ara";
            this.araBtn.ButtonTextMarginLeft = 0;
            this.araBtn.ColorContrastOnClick = 45;
            this.araBtn.ColorContrastOnHover = 45;
            this.araBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.araBtn.CustomizableEdges = borderEdges1;
            this.araBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.araBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.araBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.araBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.araBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.araBtn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.araBtn.ForeColor = System.Drawing.Color.White;
            this.araBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.araBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.araBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.araBtn.IconMarginLeft = 11;
            this.araBtn.IconPadding = 10;
            this.araBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.araBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.araBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.araBtn.IconSize = 25;
            this.araBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.araBtn.IdleBorderRadius = 1;
            this.araBtn.IdleBorderThickness = 1;
            this.araBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.araBtn.IdleIconLeftImage = null;
            this.araBtn.IdleIconRightImage = null;
            this.araBtn.IndicateFocus = false;
            this.araBtn.Location = new System.Drawing.Point(402, 500);
            this.araBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.araBtn.Name = "araBtn";
            this.araBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.araBtn.OnDisabledState.BorderRadius = 1;
            this.araBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.araBtn.OnDisabledState.BorderThickness = 1;
            this.araBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.araBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.araBtn.OnDisabledState.IconLeftImage = null;
            this.araBtn.OnDisabledState.IconRightImage = null;
            this.araBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.araBtn.onHoverState.BorderRadius = 1;
            this.araBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.araBtn.onHoverState.BorderThickness = 1;
            this.araBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.araBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.araBtn.onHoverState.IconLeftImage = null;
            this.araBtn.onHoverState.IconRightImage = null;
            this.araBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.araBtn.OnIdleState.BorderRadius = 1;
            this.araBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.araBtn.OnIdleState.BorderThickness = 1;
            this.araBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.araBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.araBtn.OnIdleState.IconLeftImage = null;
            this.araBtn.OnIdleState.IconRightImage = null;
            this.araBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.araBtn.OnPressedState.BorderRadius = 1;
            this.araBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.araBtn.OnPressedState.BorderThickness = 1;
            this.araBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.araBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.araBtn.OnPressedState.IconLeftImage = null;
            this.araBtn.OnPressedState.IconRightImage = null;
            this.araBtn.Size = new System.Drawing.Size(267, 57);
            this.araBtn.TabIndex = 67;
            this.araBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.araBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.araBtn.TextMarginLeft = 0;
            this.araBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.araBtn.UseDefaultRadiusAndThickness = true;
            this.araBtn.Click += new System.EventHandler(this.araBtn_Click);
            // 
            // ara_txt
            // 
            this.ara_txt.AcceptsReturn = false;
            this.ara_txt.AcceptsTab = false;
            this.ara_txt.AnimationSpeed = 200;
            this.ara_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ara_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ara_txt.BackColor = System.Drawing.Color.Transparent;
            this.ara_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ara_txt.BackgroundImage")));
            this.ara_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ara_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ara_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ara_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ara_txt.BorderRadius = 1;
            this.ara_txt.BorderThickness = 1;
            this.ara_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ara_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ara_txt.DefaultText = "";
            this.ara_txt.FillColor = System.Drawing.Color.White;
            this.ara_txt.HideSelection = true;
            this.ara_txt.IconLeft = null;
            this.ara_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.IconPadding = 10;
            this.ara_txt.IconRight = null;
            this.ara_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.Lines = new string[0];
            this.ara_txt.Location = new System.Drawing.Point(18, 434);
            this.ara_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ara_txt.MaxLength = 32767;
            this.ara_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.ara_txt.Modified = false;
            this.ara_txt.Multiline = false;
            this.ara_txt.Name = "ara_txt";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ara_txt.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnIdleState = stateProperties36;
            this.ara_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ara_txt.PasswordChar = '\0';
            this.ara_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ara_txt.PlaceholderText = "Aranacak Kitap İsmini Yazınız";
            this.ara_txt.ReadOnly = false;
            this.ara_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ara_txt.SelectedText = "";
            this.ara_txt.SelectionLength = 0;
            this.ara_txt.SelectionStart = 0;
            this.ara_txt.ShortcutsEnabled = true;
            this.ara_txt.Size = new System.Drawing.Size(651, 57);
            this.ara_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ara_txt.TabIndex = 68;
            this.ara_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ara_txt.TextMarginBottom = 0;
            this.ara_txt.TextMarginLeft = 3;
            this.ara_txt.TextMarginTop = 0;
            this.ara_txt.TextPlaceholder = "Aranacak Kitap İsmini Yazınız";
            this.ara_txt.UseSystemPasswordChar = false;
            this.ara_txt.WordWrap = true;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoScroll = true;
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.LightGray;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(678, 18);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(790, 538);
            this.flowLayoutPanel1.TabIndex = 70;
            // 
            // temizle_btn
            // 
            this.temizle_btn.AllowAnimations = true;
            this.temizle_btn.AllowMouseEffects = true;
            this.temizle_btn.AllowToggling = false;
            this.temizle_btn.AnimationSpeed = 200;
            this.temizle_btn.AutoGenerateColors = false;
            this.temizle_btn.AutoRoundBorders = false;
            this.temizle_btn.AutoSizeLeftIcon = true;
            this.temizle_btn.AutoSizeRightIcon = true;
            this.temizle_btn.BackColor = System.Drawing.Color.Transparent;
            this.temizle_btn.BackColor1 = System.Drawing.Color.Purple;
            this.temizle_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("temizle_btn.BackgroundImage")));
            this.temizle_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.temizle_btn.ButtonText = "Temizle";
            this.temizle_btn.ButtonTextMarginLeft = 0;
            this.temizle_btn.ColorContrastOnClick = 45;
            this.temizle_btn.ColorContrastOnHover = 45;
            this.temizle_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.temizle_btn.CustomizableEdges = borderEdges2;
            this.temizle_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.temizle_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.temizle_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.temizle_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.temizle_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.temizle_btn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.temizle_btn.ForeColor = System.Drawing.Color.White;
            this.temizle_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.temizle_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.temizle_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.temizle_btn.IconMarginLeft = 11;
            this.temizle_btn.IconPadding = 10;
            this.temizle_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.temizle_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.temizle_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.temizle_btn.IconSize = 25;
            this.temizle_btn.IdleBorderColor = System.Drawing.Color.Purple;
            this.temizle_btn.IdleBorderRadius = 1;
            this.temizle_btn.IdleBorderThickness = 1;
            this.temizle_btn.IdleFillColor = System.Drawing.Color.Purple;
            this.temizle_btn.IdleIconLeftImage = null;
            this.temizle_btn.IdleIconRightImage = null;
            this.temizle_btn.IndicateFocus = false;
            this.temizle_btn.Location = new System.Drawing.Point(18, 501);
            this.temizle_btn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.temizle_btn.Name = "temizle_btn";
            this.temizle_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.temizle_btn.OnDisabledState.BorderRadius = 1;
            this.temizle_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.temizle_btn.OnDisabledState.BorderThickness = 1;
            this.temizle_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.temizle_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.temizle_btn.OnDisabledState.IconLeftImage = null;
            this.temizle_btn.OnDisabledState.IconRightImage = null;
            this.temizle_btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.temizle_btn.onHoverState.BorderRadius = 1;
            this.temizle_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.temizle_btn.onHoverState.BorderThickness = 1;
            this.temizle_btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.temizle_btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.temizle_btn.onHoverState.IconLeftImage = null;
            this.temizle_btn.onHoverState.IconRightImage = null;
            this.temizle_btn.OnIdleState.BorderColor = System.Drawing.Color.Purple;
            this.temizle_btn.OnIdleState.BorderRadius = 1;
            this.temizle_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.temizle_btn.OnIdleState.BorderThickness = 1;
            this.temizle_btn.OnIdleState.FillColor = System.Drawing.Color.Purple;
            this.temizle_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.temizle_btn.OnIdleState.IconLeftImage = null;
            this.temizle_btn.OnIdleState.IconRightImage = null;
            this.temizle_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.temizle_btn.OnPressedState.BorderRadius = 1;
            this.temizle_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.temizle_btn.OnPressedState.BorderThickness = 1;
            this.temizle_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.temizle_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.temizle_btn.OnPressedState.IconLeftImage = null;
            this.temizle_btn.OnPressedState.IconRightImage = null;
            this.temizle_btn.Size = new System.Drawing.Size(376, 57);
            this.temizle_btn.TabIndex = 71;
            this.temizle_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.temizle_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.temizle_btn.TextMarginLeft = 0;
            this.temizle_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.temizle_btn.UseDefaultRadiusAndThickness = true;
            this.temizle_btn.Click += new System.EventHandler(this.temizle_btn_Click);
            // 
            // Kitaplar
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1486, 1134);
            this.Controls.Add(this.temizle_btn);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.yazar_txt);
            this.Controls.Add(this.ara_txt);
            this.Controls.Add(this.araBtn);
            this.Controls.Add(this.oduncDataGridView);
            this.Controls.Add(this.UyeResimBox);
            this.Controls.Add(this.ozet_txt);
            this.Controls.Add(this.tur_txt);
            this.Controls.Add(this.kitapİsim_txt);
            this.Controls.Add(this.kimlik_txt);
            this.Controls.Add(this.telefon_txt);
            this.Controls.Add(this.adres_txt);
            this.Controls.Add(this.adsoyad_txt);
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "Kitaplar";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Ödünç Kitaplar";
            this.Load += new System.EventHandler(this.Kitaplar_Load);
            ((System.ComponentModel.ISupportInitialize)(this.UyeResimBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.oduncDataGridView)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox kimlik_txt;
        private Bunifu.UI.WinForms.BunifuTextBox telefon_txt;
        private Bunifu.UI.WinForms.BunifuTextBox adres_txt;
        private Bunifu.UI.WinForms.BunifuTextBox adsoyad_txt;
        private Bunifu.UI.WinForms.BunifuTextBox ozet_txt;
        private Bunifu.UI.WinForms.BunifuTextBox tur_txt;
        private Bunifu.UI.WinForms.BunifuTextBox yazar_txt;
        private Bunifu.UI.WinForms.BunifuTextBox kitapİsim_txt;
        private System.Windows.Forms.PictureBox UyeResimBox;
        private Bunifu.UI.WinForms.BunifuDataGridView oduncDataGridView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton araBtn;
        private Bunifu.UI.WinForms.BunifuTextBox ara_txt;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton temizle_btn;
    }
}