
namespace SMARTLİBRARY
{
    partial class Yoneticiİstekler
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Yoneticiİstekler));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Temizle_Btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.uyeİsim = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.sayfa_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.yazar_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ara_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AraBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.kitapDataGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.ozet_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tur_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.isim_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.aciklama_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.kitapDataGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // Temizle_Btn
            // 
            this.Temizle_Btn.AllowAnimations = true;
            this.Temizle_Btn.AllowMouseEffects = true;
            this.Temizle_Btn.AllowToggling = false;
            this.Temizle_Btn.AnimationSpeed = 200;
            this.Temizle_Btn.AutoGenerateColors = false;
            this.Temizle_Btn.AutoRoundBorders = false;
            this.Temizle_Btn.AutoSizeLeftIcon = true;
            this.Temizle_Btn.AutoSizeRightIcon = true;
            this.Temizle_Btn.BackColor = System.Drawing.Color.Transparent;
            this.Temizle_Btn.BackColor1 = System.Drawing.Color.DarkSlateGray;
            this.Temizle_Btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Temizle_Btn.BackgroundImage")));
            this.Temizle_Btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Temizle_Btn.ButtonText = "Temizle";
            this.Temizle_Btn.ButtonTextMarginLeft = 0;
            this.Temizle_Btn.ColorContrastOnClick = 45;
            this.Temizle_Btn.ColorContrastOnHover = 45;
            this.Temizle_Btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Temizle_Btn.CustomizableEdges = borderEdges3;
            this.Temizle_Btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Temizle_Btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Temizle_Btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Temizle_Btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Temizle_Btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Temizle_Btn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.Temizle_Btn.ForeColor = System.Drawing.Color.White;
            this.Temizle_Btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Temizle_Btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Temizle_Btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Temizle_Btn.IconMarginLeft = 11;
            this.Temizle_Btn.IconPadding = 10;
            this.Temizle_Btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Temizle_Btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Temizle_Btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Temizle_Btn.IconSize = 25;
            this.Temizle_Btn.IdleBorderColor = System.Drawing.Color.DarkSlateGray;
            this.Temizle_Btn.IdleBorderRadius = 1;
            this.Temizle_Btn.IdleBorderThickness = 1;
            this.Temizle_Btn.IdleFillColor = System.Drawing.Color.DarkSlateGray;
            this.Temizle_Btn.IdleIconLeftImage = null;
            this.Temizle_Btn.IdleIconRightImage = null;
            this.Temizle_Btn.IndicateFocus = false;
            this.Temizle_Btn.Location = new System.Drawing.Point(27, 495);
            this.Temizle_Btn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Temizle_Btn.Name = "Temizle_Btn";
            this.Temizle_Btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Temizle_Btn.OnDisabledState.BorderRadius = 1;
            this.Temizle_Btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Temizle_Btn.OnDisabledState.BorderThickness = 1;
            this.Temizle_Btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Temizle_Btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Temizle_Btn.OnDisabledState.IconLeftImage = null;
            this.Temizle_Btn.OnDisabledState.IconRightImage = null;
            this.Temizle_Btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Temizle_Btn.onHoverState.BorderRadius = 1;
            this.Temizle_Btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Temizle_Btn.onHoverState.BorderThickness = 1;
            this.Temizle_Btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Temizle_Btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Temizle_Btn.onHoverState.IconLeftImage = null;
            this.Temizle_Btn.onHoverState.IconRightImage = null;
            this.Temizle_Btn.OnIdleState.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.Temizle_Btn.OnIdleState.BorderRadius = 1;
            this.Temizle_Btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Temizle_Btn.OnIdleState.BorderThickness = 1;
            this.Temizle_Btn.OnIdleState.FillColor = System.Drawing.Color.DarkSlateGray;
            this.Temizle_Btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Temizle_Btn.OnIdleState.IconLeftImage = null;
            this.Temizle_Btn.OnIdleState.IconRightImage = null;
            this.Temizle_Btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Temizle_Btn.OnPressedState.BorderRadius = 1;
            this.Temizle_Btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Temizle_Btn.OnPressedState.BorderThickness = 1;
            this.Temizle_Btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Temizle_Btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Temizle_Btn.OnPressedState.IconLeftImage = null;
            this.Temizle_Btn.OnPressedState.IconRightImage = null;
            this.Temizle_Btn.Size = new System.Drawing.Size(296, 57);
            this.Temizle_Btn.TabIndex = 123;
            this.Temizle_Btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Temizle_Btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Temizle_Btn.TextMarginLeft = 0;
            this.Temizle_Btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Temizle_Btn.UseDefaultRadiusAndThickness = true;
            this.Temizle_Btn.Click += new System.EventHandler(this.Temizle_Btn_Click);
            // 
            // uyeİsim
            // 
            this.uyeİsim.AcceptsReturn = false;
            this.uyeİsim.AcceptsTab = false;
            this.uyeİsim.AnimationSpeed = 200;
            this.uyeİsim.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.uyeİsim.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.uyeİsim.BackColor = System.Drawing.Color.Transparent;
            this.uyeİsim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("uyeİsim.BackgroundImage")));
            this.uyeİsim.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.uyeİsim.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.uyeİsim.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.uyeİsim.BorderColorIdle = System.Drawing.Color.Silver;
            this.uyeİsim.BorderRadius = 1;
            this.uyeİsim.BorderThickness = 1;
            this.uyeİsim.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.uyeİsim.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.uyeİsim.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.uyeİsim.DefaultText = "";
            this.uyeİsim.FillColor = System.Drawing.Color.White;
            this.uyeİsim.HideSelection = true;
            this.uyeİsim.IconLeft = null;
            this.uyeİsim.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.uyeİsim.IconPadding = 10;
            this.uyeİsim.IconRight = null;
            this.uyeİsim.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.uyeİsim.Lines = new string[0];
            this.uyeİsim.Location = new System.Drawing.Point(27, 429);
            this.uyeİsim.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.uyeİsim.MaxLength = 32767;
            this.uyeİsim.MinimumSize = new System.Drawing.Size(2, 2);
            this.uyeİsim.Modified = false;
            this.uyeİsim.Multiline = false;
            this.uyeİsim.Name = "uyeİsim";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.uyeİsim.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.uyeİsim.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.uyeİsim.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.uyeİsim.OnIdleState = stateProperties36;
            this.uyeİsim.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.uyeİsim.PasswordChar = '\0';
            this.uyeİsim.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.uyeİsim.PlaceholderText = "Üye İsim";
            this.uyeİsim.ReadOnly = false;
            this.uyeİsim.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.uyeİsim.SelectedText = "";
            this.uyeİsim.SelectionLength = 0;
            this.uyeİsim.SelectionStart = 0;
            this.uyeİsim.ShortcutsEnabled = true;
            this.uyeİsim.Size = new System.Drawing.Size(296, 57);
            this.uyeİsim.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.uyeİsim.TabIndex = 122;
            this.uyeİsim.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.uyeİsim.TextMarginBottom = 0;
            this.uyeİsim.TextMarginLeft = 3;
            this.uyeİsim.TextMarginTop = 0;
            this.uyeİsim.TextPlaceholder = "Üye İsim";
            this.uyeİsim.UseSystemPasswordChar = false;
            this.uyeİsim.WordWrap = true;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = global::SMARTLİBRARY.Properties.Resources.m;
            this.pictureBox2.Location = new System.Drawing.Point(426, 148);
            this.pictureBox2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(252, 274);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 120;
            this.pictureBox2.TabStop = false;
            // 
            // sayfa_txt
            // 
            this.sayfa_txt.AcceptsReturn = false;
            this.sayfa_txt.AcceptsTab = false;
            this.sayfa_txt.AnimationSpeed = 200;
            this.sayfa_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sayfa_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sayfa_txt.BackColor = System.Drawing.Color.Transparent;
            this.sayfa_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sayfa_txt.BackgroundImage")));
            this.sayfa_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.sayfa_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sayfa_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sayfa_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.sayfa_txt.BorderRadius = 1;
            this.sayfa_txt.BorderThickness = 1;
            this.sayfa_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sayfa_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sayfa_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.sayfa_txt.DefaultText = "";
            this.sayfa_txt.FillColor = System.Drawing.Color.White;
            this.sayfa_txt.HideSelection = true;
            this.sayfa_txt.IconLeft = null;
            this.sayfa_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sayfa_txt.IconPadding = 10;
            this.sayfa_txt.IconRight = null;
            this.sayfa_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sayfa_txt.Lines = new string[0];
            this.sayfa_txt.Location = new System.Drawing.Point(426, 82);
            this.sayfa_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sayfa_txt.MaxLength = 32767;
            this.sayfa_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.sayfa_txt.Modified = false;
            this.sayfa_txt.Multiline = false;
            this.sayfa_txt.Name = "sayfa_txt";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sayfa_txt.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sayfa_txt.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sayfa_txt.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sayfa_txt.OnIdleState = stateProperties40;
            this.sayfa_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.sayfa_txt.PasswordChar = '\0';
            this.sayfa_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.sayfa_txt.PlaceholderText = "Sayfa";
            this.sayfa_txt.ReadOnly = false;
            this.sayfa_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sayfa_txt.SelectedText = "";
            this.sayfa_txt.SelectionLength = 0;
            this.sayfa_txt.SelectionStart = 0;
            this.sayfa_txt.ShortcutsEnabled = true;
            this.sayfa_txt.Size = new System.Drawing.Size(252, 57);
            this.sayfa_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sayfa_txt.TabIndex = 119;
            this.sayfa_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sayfa_txt.TextMarginBottom = 0;
            this.sayfa_txt.TextMarginLeft = 3;
            this.sayfa_txt.TextMarginTop = 0;
            this.sayfa_txt.TextPlaceholder = "Sayfa";
            this.sayfa_txt.UseSystemPasswordChar = false;
            this.sayfa_txt.WordWrap = true;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoScroll = true;
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.LightGray;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(687, 14);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(706, 538);
            this.flowLayoutPanel1.TabIndex = 118;
            // 
            // yazar_txt
            // 
            this.yazar_txt.AcceptsReturn = false;
            this.yazar_txt.AcceptsTab = false;
            this.yazar_txt.AnimationSpeed = 200;
            this.yazar_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.yazar_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.yazar_txt.BackColor = System.Drawing.Color.Transparent;
            this.yazar_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("yazar_txt.BackgroundImage")));
            this.yazar_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.yazar_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.yazar_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.yazar_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.yazar_txt.BorderRadius = 1;
            this.yazar_txt.BorderThickness = 1;
            this.yazar_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.yazar_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.yazar_txt.DefaultText = "";
            this.yazar_txt.FillColor = System.Drawing.Color.White;
            this.yazar_txt.HideSelection = true;
            this.yazar_txt.IconLeft = null;
            this.yazar_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.IconPadding = 10;
            this.yazar_txt.IconRight = null;
            this.yazar_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.yazar_txt.Lines = new string[0];
            this.yazar_txt.Location = new System.Drawing.Point(426, 14);
            this.yazar_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.yazar_txt.MaxLength = 32767;
            this.yazar_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.yazar_txt.Modified = false;
            this.yazar_txt.Multiline = false;
            this.yazar_txt.Name = "yazar_txt";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.yazar_txt.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.yazar_txt.OnIdleState = stateProperties44;
            this.yazar_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.yazar_txt.PasswordChar = '\0';
            this.yazar_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.yazar_txt.PlaceholderText = "Yazar";
            this.yazar_txt.ReadOnly = false;
            this.yazar_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.yazar_txt.SelectedText = "";
            this.yazar_txt.SelectionLength = 0;
            this.yazar_txt.SelectionStart = 0;
            this.yazar_txt.ShortcutsEnabled = true;
            this.yazar_txt.Size = new System.Drawing.Size(252, 57);
            this.yazar_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.yazar_txt.TabIndex = 112;
            this.yazar_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.yazar_txt.TextMarginBottom = 0;
            this.yazar_txt.TextMarginLeft = 3;
            this.yazar_txt.TextMarginTop = 0;
            this.yazar_txt.TextPlaceholder = "Yazar";
            this.yazar_txt.UseSystemPasswordChar = false;
            this.yazar_txt.WordWrap = true;
            // 
            // ara_txt
            // 
            this.ara_txt.AcceptsReturn = false;
            this.ara_txt.AcceptsTab = false;
            this.ara_txt.AnimationSpeed = 200;
            this.ara_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ara_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ara_txt.BackColor = System.Drawing.Color.Transparent;
            this.ara_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ara_txt.BackgroundImage")));
            this.ara_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ara_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ara_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ara_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ara_txt.BorderRadius = 1;
            this.ara_txt.BorderThickness = 1;
            this.ara_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ara_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ara_txt.DefaultText = "";
            this.ara_txt.FillColor = System.Drawing.Color.White;
            this.ara_txt.HideSelection = true;
            this.ara_txt.IconLeft = null;
            this.ara_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.IconPadding = 10;
            this.ara_txt.IconRight = null;
            this.ara_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ara_txt.Lines = new string[0];
            this.ara_txt.Location = new System.Drawing.Point(332, 429);
            this.ara_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ara_txt.MaxLength = 32767;
            this.ara_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.ara_txt.Modified = false;
            this.ara_txt.Multiline = false;
            this.ara_txt.Name = "ara_txt";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ara_txt.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ara_txt.OnIdleState = stateProperties48;
            this.ara_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ara_txt.PasswordChar = '\0';
            this.ara_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ara_txt.PlaceholderText = "Kitap Ara";
            this.ara_txt.ReadOnly = false;
            this.ara_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ara_txt.SelectedText = "";
            this.ara_txt.SelectionLength = 0;
            this.ara_txt.SelectionStart = 0;
            this.ara_txt.ShortcutsEnabled = true;
            this.ara_txt.Size = new System.Drawing.Size(346, 57);
            this.ara_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ara_txt.TabIndex = 117;
            this.ara_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ara_txt.TextMarginBottom = 0;
            this.ara_txt.TextMarginLeft = 3;
            this.ara_txt.TextMarginTop = 0;
            this.ara_txt.TextPlaceholder = "Kitap Ara";
            this.ara_txt.UseSystemPasswordChar = false;
            this.ara_txt.WordWrap = true;
            this.ara_txt.TextChanged += new System.EventHandler(this.ara_txt_TextChanged);
            // 
            // AraBtn
            // 
            this.AraBtn.AllowAnimations = true;
            this.AraBtn.AllowMouseEffects = true;
            this.AraBtn.AllowToggling = false;
            this.AraBtn.AnimationSpeed = 200;
            this.AraBtn.AutoGenerateColors = false;
            this.AraBtn.AutoRoundBorders = false;
            this.AraBtn.AutoSizeLeftIcon = true;
            this.AraBtn.AutoSizeRightIcon = true;
            this.AraBtn.BackColor = System.Drawing.Color.Transparent;
            this.AraBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.AraBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AraBtn.BackgroundImage")));
            this.AraBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.ButtonText = "Ara";
            this.AraBtn.ButtonTextMarginLeft = 0;
            this.AraBtn.ColorContrastOnClick = 45;
            this.AraBtn.ColorContrastOnHover = 45;
            this.AraBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AraBtn.CustomizableEdges = borderEdges4;
            this.AraBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AraBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AraBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AraBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AraBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AraBtn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.AraBtn.ForeColor = System.Drawing.Color.White;
            this.AraBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AraBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AraBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AraBtn.IconMarginLeft = 11;
            this.AraBtn.IconPadding = 10;
            this.AraBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AraBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AraBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AraBtn.IconSize = 25;
            this.AraBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.IdleBorderRadius = 1;
            this.AraBtn.IdleBorderThickness = 1;
            this.AraBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.IdleIconLeftImage = null;
            this.AraBtn.IdleIconRightImage = null;
            this.AraBtn.IndicateFocus = false;
            this.AraBtn.Location = new System.Drawing.Point(332, 495);
            this.AraBtn.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.AraBtn.Name = "AraBtn";
            this.AraBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AraBtn.OnDisabledState.BorderRadius = 1;
            this.AraBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnDisabledState.BorderThickness = 1;
            this.AraBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AraBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AraBtn.OnDisabledState.IconLeftImage = null;
            this.AraBtn.OnDisabledState.IconRightImage = null;
            this.AraBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AraBtn.onHoverState.BorderRadius = 1;
            this.AraBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.onHoverState.BorderThickness = 1;
            this.AraBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AraBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.onHoverState.IconLeftImage = null;
            this.AraBtn.onHoverState.IconRightImage = null;
            this.AraBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.OnIdleState.BorderRadius = 1;
            this.AraBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnIdleState.BorderThickness = 1;
            this.AraBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AraBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.OnIdleState.IconLeftImage = null;
            this.AraBtn.OnIdleState.IconRightImage = null;
            this.AraBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AraBtn.OnPressedState.BorderRadius = 1;
            this.AraBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AraBtn.OnPressedState.BorderThickness = 1;
            this.AraBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AraBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AraBtn.OnPressedState.IconLeftImage = null;
            this.AraBtn.OnPressedState.IconRightImage = null;
            this.AraBtn.Size = new System.Drawing.Size(345, 57);
            this.AraBtn.TabIndex = 116;
            this.AraBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AraBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AraBtn.TextMarginLeft = 0;
            this.AraBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AraBtn.UseDefaultRadiusAndThickness = true;
            this.AraBtn.Click += new System.EventHandler(this.AraBtn_Click);
            // 
            // kitapDataGridView
            // 
            this.kitapDataGridView.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.kitapDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.kitapDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.kitapDataGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.kitapDataGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.kitapDataGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.kitapDataGridView.ColumnHeadersHeight = 40;
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.kitapDataGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.kitapDataGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.kitapDataGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.Name = null;
            this.kitapDataGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.kitapDataGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.kitapDataGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.kitapDataGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.kitapDataGridView.DefaultCellStyle = dataGridViewCellStyle6;
            this.kitapDataGridView.EnableHeadersVisualStyles = false;
            this.kitapDataGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.kitapDataGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.kitapDataGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.kitapDataGridView.HeaderForeColor = System.Drawing.Color.White;
            this.kitapDataGridView.Location = new System.Drawing.Point(27, 562);
            this.kitapDataGridView.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.kitapDataGridView.Name = "kitapDataGridView";
            this.kitapDataGridView.RowHeadersVisible = false;
            this.kitapDataGridView.RowHeadersWidth = 62;
            this.kitapDataGridView.RowTemplate.Height = 40;
            this.kitapDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.kitapDataGridView.Size = new System.Drawing.Size(1366, 342);
            this.kitapDataGridView.TabIndex = 115;
            this.kitapDataGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.kitapDataGridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.kitapDataGridView_CellClick);
            // 
            // ozet_txt
            // 
            this.ozet_txt.AcceptsReturn = false;
            this.ozet_txt.AcceptsTab = false;
            this.ozet_txt.AnimationSpeed = 200;
            this.ozet_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ozet_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ozet_txt.BackColor = System.Drawing.Color.Transparent;
            this.ozet_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ozet_txt.BackgroundImage")));
            this.ozet_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ozet_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ozet_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ozet_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.ozet_txt.BorderRadius = 1;
            this.ozet_txt.BorderThickness = 1;
            this.ozet_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ozet_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ozet_txt.DefaultText = "";
            this.ozet_txt.FillColor = System.Drawing.Color.White;
            this.ozet_txt.HideSelection = true;
            this.ozet_txt.IconLeft = null;
            this.ozet_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.IconPadding = 10;
            this.ozet_txt.IconRight = null;
            this.ozet_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ozet_txt.Lines = new string[0];
            this.ozet_txt.Location = new System.Drawing.Point(27, 148);
            this.ozet_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ozet_txt.MaxLength = 32767;
            this.ozet_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.ozet_txt.Modified = false;
            this.ozet_txt.Multiline = true;
            this.ozet_txt.Name = "ozet_txt";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ozet_txt.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ozet_txt.OnIdleState = stateProperties52;
            this.ozet_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.ozet_txt.PasswordChar = '\0';
            this.ozet_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ozet_txt.PlaceholderText = "Özet";
            this.ozet_txt.ReadOnly = false;
            this.ozet_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ozet_txt.SelectedText = "";
            this.ozet_txt.SelectionLength = 0;
            this.ozet_txt.SelectionStart = 0;
            this.ozet_txt.ShortcutsEnabled = true;
            this.ozet_txt.Size = new System.Drawing.Size(390, 142);
            this.ozet_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ozet_txt.TabIndex = 114;
            this.ozet_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ozet_txt.TextMarginBottom = 0;
            this.ozet_txt.TextMarginLeft = 3;
            this.ozet_txt.TextMarginTop = 0;
            this.ozet_txt.TextPlaceholder = "Özet";
            this.ozet_txt.UseSystemPasswordChar = false;
            this.ozet_txt.WordWrap = true;
            // 
            // tur_txt
            // 
            this.tur_txt.AcceptsReturn = false;
            this.tur_txt.AcceptsTab = false;
            this.tur_txt.AnimationSpeed = 200;
            this.tur_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tur_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tur_txt.BackColor = System.Drawing.Color.Transparent;
            this.tur_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tur_txt.BackgroundImage")));
            this.tur_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tur_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tur_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tur_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.tur_txt.BorderRadius = 1;
            this.tur_txt.BorderThickness = 1;
            this.tur_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tur_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tur_txt.DefaultText = "";
            this.tur_txt.FillColor = System.Drawing.Color.White;
            this.tur_txt.HideSelection = true;
            this.tur_txt.IconLeft = null;
            this.tur_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.IconPadding = 10;
            this.tur_txt.IconRight = null;
            this.tur_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tur_txt.Lines = new string[0];
            this.tur_txt.Location = new System.Drawing.Point(27, 82);
            this.tur_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tur_txt.MaxLength = 32767;
            this.tur_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.tur_txt.Modified = false;
            this.tur_txt.Multiline = false;
            this.tur_txt.Name = "tur_txt";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tur_txt.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tur_txt.OnIdleState = stateProperties56;
            this.tur_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.tur_txt.PasswordChar = '\0';
            this.tur_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.tur_txt.PlaceholderText = "Tür";
            this.tur_txt.ReadOnly = false;
            this.tur_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tur_txt.SelectedText = "";
            this.tur_txt.SelectionLength = 0;
            this.tur_txt.SelectionStart = 0;
            this.tur_txt.ShortcutsEnabled = true;
            this.tur_txt.Size = new System.Drawing.Size(390, 57);
            this.tur_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tur_txt.TabIndex = 113;
            this.tur_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tur_txt.TextMarginBottom = 0;
            this.tur_txt.TextMarginLeft = 3;
            this.tur_txt.TextMarginTop = 0;
            this.tur_txt.TextPlaceholder = "Tür";
            this.tur_txt.UseSystemPasswordChar = false;
            this.tur_txt.WordWrap = true;
            // 
            // isim_txt
            // 
            this.isim_txt.AcceptsReturn = false;
            this.isim_txt.AcceptsTab = false;
            this.isim_txt.AnimationSpeed = 200;
            this.isim_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.isim_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.isim_txt.BackColor = System.Drawing.Color.Transparent;
            this.isim_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("isim_txt.BackgroundImage")));
            this.isim_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.isim_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.isim_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.isim_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.isim_txt.BorderRadius = 1;
            this.isim_txt.BorderThickness = 1;
            this.isim_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.isim_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.isim_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.isim_txt.DefaultText = "";
            this.isim_txt.FillColor = System.Drawing.Color.White;
            this.isim_txt.HideSelection = true;
            this.isim_txt.IconLeft = null;
            this.isim_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.isim_txt.IconPadding = 10;
            this.isim_txt.IconRight = null;
            this.isim_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.isim_txt.Lines = new string[0];
            this.isim_txt.Location = new System.Drawing.Point(27, 14);
            this.isim_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.isim_txt.MaxLength = 32767;
            this.isim_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.isim_txt.Modified = false;
            this.isim_txt.Multiline = false;
            this.isim_txt.Name = "isim_txt";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.isim_txt.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.isim_txt.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.isim_txt.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.isim_txt.OnIdleState = stateProperties60;
            this.isim_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.isim_txt.PasswordChar = '\0';
            this.isim_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.isim_txt.PlaceholderText = "Kitap İsim";
            this.isim_txt.ReadOnly = false;
            this.isim_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.isim_txt.SelectedText = "";
            this.isim_txt.SelectionLength = 0;
            this.isim_txt.SelectionStart = 0;
            this.isim_txt.ShortcutsEnabled = true;
            this.isim_txt.Size = new System.Drawing.Size(390, 57);
            this.isim_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.isim_txt.TabIndex = 111;
            this.isim_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.isim_txt.TextMarginBottom = 0;
            this.isim_txt.TextMarginLeft = 3;
            this.isim_txt.TextMarginTop = 0;
            this.isim_txt.TextPlaceholder = "Kitap İsim";
            this.isim_txt.UseSystemPasswordChar = false;
            this.isim_txt.WordWrap = true;
            // 
            // aciklama_txt
            // 
            this.aciklama_txt.AcceptsReturn = false;
            this.aciklama_txt.AcceptsTab = false;
            this.aciklama_txt.AnimationSpeed = 200;
            this.aciklama_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.aciklama_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.aciklama_txt.BackColor = System.Drawing.Color.Transparent;
            this.aciklama_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("aciklama_txt.BackgroundImage")));
            this.aciklama_txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.aciklama_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.aciklama_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.aciklama_txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.aciklama_txt.BorderRadius = 1;
            this.aciklama_txt.BorderThickness = 1;
            this.aciklama_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.aciklama_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.aciklama_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.aciklama_txt.DefaultText = "";
            this.aciklama_txt.FillColor = System.Drawing.Color.White;
            this.aciklama_txt.HideSelection = true;
            this.aciklama_txt.IconLeft = null;
            this.aciklama_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.aciklama_txt.IconPadding = 10;
            this.aciklama_txt.IconRight = null;
            this.aciklama_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.aciklama_txt.Lines = new string[0];
            this.aciklama_txt.Location = new System.Drawing.Point(27, 298);
            this.aciklama_txt.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.aciklama_txt.MaxLength = 32767;
            this.aciklama_txt.MinimumSize = new System.Drawing.Size(2, 2);
            this.aciklama_txt.Modified = false;
            this.aciklama_txt.Multiline = true;
            this.aciklama_txt.Name = "aciklama_txt";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.aciklama_txt.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.aciklama_txt.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.aciklama_txt.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.aciklama_txt.OnIdleState = stateProperties64;
            this.aciklama_txt.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.aciklama_txt.PasswordChar = '\0';
            this.aciklama_txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.aciklama_txt.PlaceholderText = "Açıklama";
            this.aciklama_txt.ReadOnly = false;
            this.aciklama_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.aciklama_txt.SelectedText = "";
            this.aciklama_txt.SelectionLength = 0;
            this.aciklama_txt.SelectionStart = 0;
            this.aciklama_txt.ShortcutsEnabled = true;
            this.aciklama_txt.Size = new System.Drawing.Size(390, 122);
            this.aciklama_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.aciklama_txt.TabIndex = 124;
            this.aciklama_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.aciklama_txt.TextMarginBottom = 0;
            this.aciklama_txt.TextMarginLeft = 3;
            this.aciklama_txt.TextMarginTop = 0;
            this.aciklama_txt.TextPlaceholder = "Açıklama";
            this.aciklama_txt.UseSystemPasswordChar = false;
            this.aciklama_txt.WordWrap = true;
            // 
            // Yoneticiİstekler
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1402, 922);
            this.Controls.Add(this.aciklama_txt);
            this.Controls.Add(this.Temizle_Btn);
            this.Controls.Add(this.uyeİsim);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.sayfa_txt);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.yazar_txt);
            this.Controls.Add(this.ara_txt);
            this.Controls.Add(this.AraBtn);
            this.Controls.Add(this.kitapDataGridView);
            this.Controls.Add(this.ozet_txt);
            this.Controls.Add(this.tur_txt);
            this.Controls.Add(this.isim_txt);
            this.Name = "Yoneticiİstekler";
            this.Text = "İstekler";
            this.Load += new System.EventHandler(this.Yoneticiİstekler_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.kitapDataGridView)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Temizle_Btn;
        private Bunifu.UI.WinForms.BunifuTextBox uyeİsim;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuTextBox sayfa_txt;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox yazar_txt;
        private Bunifu.UI.WinForms.BunifuTextBox ara_txt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AraBtn;
        private Bunifu.UI.WinForms.BunifuDataGridView kitapDataGridView;
        private Bunifu.UI.WinForms.BunifuTextBox ozet_txt;
        private Bunifu.UI.WinForms.BunifuTextBox tur_txt;
        private Bunifu.UI.WinForms.BunifuTextBox isim_txt;
        private Bunifu.UI.WinForms.BunifuTextBox aciklama_txt;
    }
}